#include "openu5/dungeon_encounters.h"
#include "openu5/dungeon.h"
#include "openu5/rest.h"
#include "openu5/gameplay_save.h"
#include "openu5/look.h"
#include "openu5/outdoor.h"
#include "openu5/persistence.h"
#include "quest_combat_fixture.h"
#include <fstream>
#include <iostream>
#include <memory>
using namespace openu5;
using save::Json;
static Json read(const char *path){std::ifstream f(path);std::string s((std::istreambuf_iterator<char>(f)),{});Json j;if(save::parse_json(s,j)!=save::JsonError::None)std::exit(2);return j;}
struct Objects {Json values;CommandContext *ctx;};
static const char *plot_names[]={"amulet","crown","sceptre","woodenBox","carpet","shard-falsehood","shard-hatred","shard-cowardice"};
static QuestObject object_read(void *p,size_t i){const auto &v=static_cast<Objects*>(p)->values.at(i);QuestObject o;o.location=int32_t(v["location"].integer());o.floor=int32_t(v["floor"].integer());o.x=int32_t(v["x"].integer());o.y=int32_t(v["y"].integer());o.tile=int32_t(v["tile"].integer());o.plot=v["kind"].string==u"plot";o.shadowlord=v["kind"].string==u"shadowlord";o.search=v["kind"].string==u"search";o.plot_z=int32_t(v["plotZ"].integer(-1));for(int j=0;j<8;++j)if(v["plotItem"].string==Json(plot_names[j]).string)o.item=PlotItem(j);o.slot=int32_t(v["slot"].integer(-1));o.hull=int32_t(v["hull"].integer());o.skiffs=int32_t(v["skiffs"].integer());o.torch=v["kind"].string==u"torch";o.ship=v["kind"].string==u"ship";o.prop=v["kind"].string==u"prop";o.chest=v["kind"].string==u"chest";o.loot=v["kind"].string==u"loot";o.contents=int32_t(v["contents"].integer());o.trapped=v["trapped"].truth();o.item_id=int32_t(v["loot"]["id"].integer());o.quality=int32_t(v["loot"]["qty"].integer());return o;}
static void object_append(void *p,const QuestObject &o){Json v=Json::object();v["location"]=Json(o.location);v["floor"]=Json(o.floor);v["x"]=Json(o.x);v["y"]=Json(o.y);v["tile"]=Json(o.tile);v["kind"]=Json(o.plot?"plot":o.shadowlord?"shadowlord":o.chest?"chest":o.ship?"ship":o.loot?"loot":"prop");if(o.plot){v["plotItem"]=Json(plot_names[int(o.item)]);if(o.plot_z>=0)v["plotZ"]=Json(o.plot_z);}if(o.chest){v["contents"]=Json(o.contents);v["trapped"]=Json(o.trapped);}if(o.slot>=0)v["slot"]=Json(o.slot);if(o.ship){v["hull"]=Json(o.hull);v["skiffs"]=Json(o.skiffs);}if(o.loot){v["contents"]=Json(o.contents);v["loot"]=Json::object();v["loot"]["id"]=Json(o.item_id);v["loot"]["qty"]=Json(o.quality);const char *categories[]={"unknown","chest","gold","potion","scroll","equipment","equipment","keys","gems","equipment","equipment","equipment","equipment","torches","sandalwood","food"};v["loot"]["category"]=Json(o.item_id>=0&&o.item_id<16?categories[o.item_id]:"unknown");}static_cast<Objects*>(p)->values.values.push_back(std::move(v));}
static Json combat_snapshot(const CombatContext &c,bool active){
    Json b=Json::object();b["active"]=Json(active);if(!active)return b;const auto &s=c.combat;
    b["seed"]=Json(s.rng.get_seed());b["map"]=Json(s.map.index);b["tiles"]=Json::array();for(auto tile:s.map.tiles)b["tiles"].values.emplace_back(tile);
    b["current"]=Json(s.current<0?-1:s.actors[s.current].id);b["actors"]=Json::array();
    for(int i=0;i<s.count;++i){auto &a=s.actors[i];Json row=Json::array();for(int n:{a.id,int(a.member),a.enemy?a.enemy->index:-1,int(a.position.x),int(a.position.y),a.hp,a.max_hp,a.strength,a.dexterity,a.intelligence,a.defense,a.attack,a.range,int(a.status),int(a.speed),int(a.counter)})row.values.emplace_back(n);row.values.emplace_back(a.sleeping);row.values.emplace_back(a.invisible);row.values.emplace_back(a.charmed);row.values.emplace_back(a.render_tile);b["actors"].values.push_back(std::move(row));}return b;
}
static void emit(void *p,const GameEvent &e){
    if(e.combat){const auto &v=*e.combat;const char *names[]={"message","echo","moved","attacked","died","turn","ended","projectile","quake","line-spray"};Json row=Json::array();row.values.emplace_back(names[int(v.kind)]);row.values.emplace_back(v.text?v.text:"");for(int n:{v.actor,v.target,v.x,v.y,v.damage})row.values.emplace_back(n);(*static_cast<Json*>(p))["combatEvents"].values.push_back(std::move(row));return;}
    Json row=Json::object();const char *kind=nullptr;
    switch(e.kind){
    case GameEventKind::Refuge:kind="refuge";break;case GameEventKind::CellProjectile:kind="cell-projectile";break;case GameEventKind::MapReveal:kind="map-reveal";break;case GameEventKind::Zodiac:kind="zodiac-view";break;case GameEventKind::GemView:kind="gem-view";break;case GameEventKind::CrystalBallPrompt:kind="crystal-ball-prompt";break;case GameEventKind::WellDropPrompt:kind="well-drop-prompt";break;case GameEventKind::FountainDrinkPrompt:kind="fountain-drink-prompt";break;case GameEventKind::WellWishPrompt:kind="well-wish-prompt";break;
    case GameEventKind::Message:kind="message";break;case GameEventKind::Moved:kind="moved";break;case GameEventKind::MapChanged:kind="map-changed";break;case GameEventKind::PartyChanged:kind="party-changed";break;case GameEventKind::WalkEcho:kind="walk-echo";break;case GameEventKind::Sfx:kind="sfx";break;case GameEventKind::PoisonTick:kind="poison-tick";break;case GameEventKind::Quake:kind="quake";break;case GameEventKind::CombatStarted:kind="combat-started";break;case GameEventKind::CombatEnded:kind="combat-ended";break;case GameEventKind::TrollSneak:kind="troll-sneak";break;case GameEventKind::TrollTollPrompt:kind="troll-toll-prompt";break;case GameEventKind::MagicCeremony:kind="magic-ceremony";break;default:kind="unknown";break;}
    row["kind"]=Json(kind);row["text"]=Json(e.text?e.text:"");if(e.kind==GameEventKind::TrollTollPrompt)row["toll"]=Json(e.note);if(e.kind==GameEventKind::MagicCeremony)row["ceremony"]=Json(e.note);
    if(e.kind==GameEventKind::PoisonTick){row["slots"]=Json::array();for(uint8_t i=0;i<e.slot_count;++i)row["slots"].values.emplace_back(e.slots[i]);}
    if(e.sign){row["sign"]=Json(true);row["raw"]=Json::array();for(size_t i=0;i<e.sign_raw_size;++i)row["raw"].values.emplace_back(e.sign_raw[i]);}if(e.kind==GameEventKind::CellProjectile){auto &v=row["projectile"];v=Json::object();v["fromDx"]=Json(e.projectile.from_dx);v["fromDy"]=Json(e.projectile.from_dy);v["toDx"]=Json(e.projectile.to_dx);v["toDy"]=Json(e.projectile.to_dy);}if(e.kind==GameEventKind::MapReveal)row["frames"]=Json(e.note);if(e.gem_from_crystal)row["crystal"]=Json(true);
    if(e.zodiac){auto &v=row["zodiac"];v=Json::object();v["bgStars"]=Json::array();for(auto &s:e.zodiac->stars){Json j=Json::object();j["x"]=Json(s.x);j["y"]=Json(s.y);v["bgStars"].values.push_back(j);}v["signs"]=Json::array();for(auto &s:e.zodiac->signs){Json j=Json::object();j["starX"]=Json(s.star_x);j["lineX"]=Json(s.line_x);j["y"]=Json(s.y);j["hasLine"]=Json(s.has_line);v["signs"].values.push_back(j);}}
    if(e.refuge){auto &v=row["refuge"];v=Json::object();v["beats"]=Json::array();for(auto &beat:e.refuge->beats){Json b=Json::object();if(beat.scene)b["scene"]=Json(beat.scene);if(beat.message)b["message"]=Json(beat.message);if(beat.sfx){b["sfx"]=Json::object();b["sfx"]["id"]=Json(beat.sfx);}if(beat.delay>=0)b["delayUnits"]=Json(beat.delay);v["beats"].values.push_back(std::move(b));}}
    if(e.troll_sneak){row["beats"]=Json::array();for(uint8_t i=0;i<e.troll_sneak->count;++i){auto &b=e.troll_sneak->beats[i];Json v=Json::array();v.values.emplace_back(b.text);v.values.emplace_back(b.pause_units);v.values.emplace_back(b.append);row["beats"].values.push_back(std::move(v));}}
    (*static_cast<Json *>(p))["events"].values.push_back(std::move(row));
}
int main(int argc,char **argv){
    if(argc!=4)return 2;QuestCombatFixture assets;auto data=read(argv[3]);assets.load(data);std::vector<std::string> karma;for(auto &v:data["karma"].values)karma.push_back("\""+QuestCombatFixture::text(v)+"\"");std::vector<std::string> descriptions;for(auto &s:data["descriptions"].values)descriptions.push_back(std::string(s.string.begin(),s.string.end()));
    std::vector<uint8_t> real(65536);std::ifstream mapfile("native/core/build-gameplay/overworld.bin",std::ios::binary);mapfile.read(reinterpret_cast<char *>(real.data()),65536);if(!mapfile)return 3;
    std::ifstream input(argv[1]);std::ofstream output(argv[2]);std::string line;
    while(std::getline(input,line)){
        Json q;if(save::parse_json(line,q)!=save::JsonError::None)return 4;
        auto game=std::make_unique<GameState>();auto &g=*game;TurnState t;if(save::restore_core(q["state"],g,t)!=save::Error::None)return 5;g.rng.seed(uint32_t(q["seed"].integer()));
        std::vector<uint8_t> tiles=q["real"].truth()?real:std::vector<uint8_t>(65536,uint8_t(q["tile"].integer(5)));
        if(q.has("small"))for(int y=0;y<32;++y)for(int x=0;x<32;++x)tiles[y*256+x]=uint8_t(q["small"].at(y).at(x).integer());
        for(const auto &edit:q["edits"].values)tiles[size_t(edit.at(1).integer()*256+edit.at(0).integer())]=uint8_t(edit.at(2).integer());
        WorldData world;world.overworld=world.underworld=tiles.data();world.overworld_size=world.underworld_size=tiles.size();std::vector<uint8_t> small(1024);for(int y=0;y<32;++y)for(int x=0;x<32;++x)small[y*32+x]=tiles[y*256+x];MapData sm{g.position.map,small.data(),small.size()};if(g.position.map.location){world.small_maps=&sm;world.small_map_count=1;}TravelState travel;CommandState commands;CommandContext ctx{g,t,travel,commands,world};
        const bool has_npcs=q.has("npcs");std::vector<NpcSlot> slots;for(auto &v:q["npcs"].values){NpcSlot n;n.slot=uint8_t(v["slot"].integer());n.type=uint8_t(v["type"].integer());n.dialog=uint8_t(v["dialogNumber"].integer());for(int i=0;i<3;++i){n.ai[i]=uint8_t(v["aiTypes"].at(i).integer());n.x[i]=uint8_t(v["x"].at(i).integer());n.y[i]=uint8_t(v["y"].at(i).integer());n.z[i]=uint8_t(v["z"].at(i).integer());}for(int i=0;i<4;++i)n.times[i]=uint8_t(v["times"].at(i).integer());slots.push_back(n);}auto actors=std::make_unique<NpcActors>();auto path=std::make_unique<NpcScanGrid>();if(has_npcs){enter_npc_map(*actors,slots.data(),slots.size(),g.position.map.location,uint8_t(g.time.hour),g.npc_dead[g.position.map.location-1]);ctx.actors=actors.get();ctx.npc_scratch=path.get();}
        auto state=std::make_unique<CombatState>();std::vector<CombatActor> overflow(128);state->actors.overflow=overflow.data();state->actors.overflow_capacity=int32_t(overflow.size());CombatContext combat{g,t,*state,assets.resources.tables};combat.enemy_defs=assets.enemy_ptrs.data();combat.enemy_def_count=assets.enemy_ptrs.size();
        LookServices look;look.context=&descriptions;look.describe=[](void *p,int32_t tile){auto &v=*static_cast<std::vector<std::string>*>(p);return tile>=0&&size_t(tile)<v.size()?v[tile].c_str():"";};ctx.look=&look;
        struct SignData {const Json *q;std::string text;std::vector<uint8_t> raw;};SignData sign{&q,QuestCombatFixture::text(q["sign"]["text"]),{}};for(auto &v:q["sign"]["raw"].values)sign.raw.push_back(uint8_t(v.integer()));struct LookData {std::vector<std::string> *descriptions;SignData *sign;};LookData ld{&descriptions,&sign};look.context=&ld;look.describe=[](void *p,int32_t tile){auto &v=*static_cast<LookData*>(p)->descriptions;return tile>=0&&size_t(tile)<v.size()?v[tile].c_str():"";};look.sign=[](void *p,MapId map,int32_t x,int32_t y){auto &v=*static_cast<LookData*>(p)->sign;auto &s=(*v.q)["sign"];if(!v.q->has("sign")||map.location!=s["location"].integer()||map.floor!=s["floor"].integer()||x!=s["x"].integer()||y!=s["y"].integer())return LookSign{};return LookSign{v.text.c_str(),v.raw.data(),v.raw.size()};};
        RestServices rest;rest.context=&karma;rest.karma_record=[](void *p,int32_t i){return static_cast<std::vector<std::string>*>(p)->at(size_t(i)).c_str();};ctx.rest_services=&rest;
        OutdoorServices outdoor;outdoor.combat=&combat;outdoor.resources=&assets.resources;ctx.outdoor=&outdoor;
        WorldTerrain terrain;ctx.terrain=&terrain;if(save::restore_terrain(q["state"],terrain)!=save::Error::None)return 12;terrain.refresh(world,g);Objects objects{q["state"]["worldObjects"],&ctx};QuestWorldServices quest;quest.context=&objects;quest.count=[](void *p){return static_cast<Objects*>(p)->values.values.size();};quest.read=object_read;
        quest.write=[](void *p,size_t i,const QuestObject &o){auto &v=static_cast<Objects*>(p)->values.values[i];if(o.plot){v["plotItem"]=Json(plot_names[int(o.item)]);if(o.plot_z>=0)v["plotZ"]=Json(o.plot_z);}if(o.chest){v["contents"]=Json(o.contents);v["trapped"]=Json(o.trapped);}if(o.slot>=0)v["slot"]=Json(o.slot);if(o.chest||o.loot){v["contents"]=Json(o.contents);if(v.has("trapped")||o.trapped)v["trapped"]=Json(o.trapped);}};quest.reserve=[](void *p,size_t n){auto &v=static_cast<Objects*>(p)->values.values;v.reserve(v.size()+n);return true;};quest.append=object_append;quest.erase=[](void *p,size_t i){auto &v=static_cast<Objects*>(p)->values.values;v.erase(v.begin()+ptrdiff_t(i));};ctx.quest_world=&quest;quest.encounter=&combat;quest.combat_resources=&assets.resources;
        quest.tile_at=[](void *p,int32_t x,int32_t y){auto &c=*static_cast<Objects*>(p)->ctx;return c.terrain->raw(c.world,c.game.position.map,x,y);};
        quest.volatile_tile=[](void *p,int32_t x,int32_t y,int32_t tile){auto &c=*static_cast<Objects*>(p)->ctx;c.terrain->set(c.game.position.map,x,y,tile);};
        quest.persistent_tile=[](void *p,int32_t x,int32_t y,int32_t tile){auto &c=*static_cast<Objects*>(p)->ctx;c.terrain->set(c.game.position.map,x,y,tile,true);};
        std::vector<ShardSpawn> spawns;for(auto &v:data["shardSpawns"].values)spawns.push_back({int32_t(v["x"].integer()),int32_t(v["y"].integer()),int32_t(v["z"].integer())});quest.spawns=spawns.data();quest.spawn_count=spawns.size();
        std::vector<Moonstone> stones;for(auto &s:q["state"]["moonstones"].values)stones.push_back({uint8_t(s["x"].integer()),uint8_t(s["y"].integer()),int16_t(s["z"].integer()),uint8_t(s["location"].integer()),s["buried"].truth()});quest.moonstones=stones.data();quest.moonstone_count=stones.size();
        auto transport=world_transport_services(ctx);ctx.transport_services=&transport;
        if(save::restore_gameplay(q["state"],commands,outdoor)!=save::Error::None)return 9;
        auto dungeon=std::make_unique<DungeonState>();auto dscratch=std::make_unique<DungeonScratch>();DungeonContext dc{*dungeon,*dscratch};
        if(q.has("dungeon")){auto &d=q["dungeon"];dungeon->active=true;dungeon->pos={uint8_t(d["location"].integer()),3,3,3,DungeonFacing::North};for(size_t i=0;i<512;++i)dungeon->cells[i]=uint8_t(d["cells"].at(i).integer());ctx.dungeon=true;ctx.dungeon_context=&dc;}
        auto dungeonAssets=std::make_unique<QuestCombatFixture>();auto encounters=std::make_unique<DungeonEncounters>();std::vector<uint8_t> roomSprites;DungeonArena room;if(q.has("room")){Json input=Json::object();input["combatMaps"]=Json::array();input["combatMaps"].values.push_back(q["room"]);dungeonAssets->load(input);for(auto &u:q["room"]["units"].values)roomSprites.push_back(uint8_t(u["sprite"].integer()));room={&dungeonAssets->maps[0],roomSprites.data()};encounters->combat=&combat;encounters->arenas=&room;encounters->count=1;dc.encounters=encounters.get();}
        if(q.has("dungeon")&&q["dungeon"].has("wanderer")){dungeon->wanderer.type=uint8_t(q["dungeon"]["wanderer"].integer());dungeon->wanderer.x=3;dungeon->wanderer.y=2;dungeon->wanderer.floor=3;encounters->combat=&combat;dc.encounters=encounters.get();}
        Json result=Json::array();
        for(const auto &action:q["actions"].values){
            Json step=Json::object();step["events"]=Json::array();step["combatEvents"]=Json::array();ctx.events={&step,emit};
            combat.events={&step["combatEvents"],[](void *p,const CombatEvent &e){const char *names[]={"message","echo","moved","attacked","died","turn","ended","projectile","quake","line-spray"};Json row=Json::array();row.values.emplace_back(names[int(e.kind)]);row.values.emplace_back(e.text?e.text:"");for(int n:{e.actor,e.target,e.x,e.y,e.damage})row.values.emplace_back(n);static_cast<Json *>(p)->values.push_back(std::move(row));}};
            const auto kind=action["kind"].string;
            if(kind==u"end"){if(ctx.combat&&finish_encounter_combat(ctx,*state)!=CombatResult::Ok)return 6;}
            else if(kind==u"fight"||kind==u"flee"||kind==u"hold"||kind==u"escape"||kind==u"quick"){
                for(int i=0;i<action["repeat"].integer(1);++i){auto *u=current_combat_actor(combat);if(!u)break;CombatResult status;
                    if(u->member==255)status=combat_action(combat,CombatAction::EnemyStep);
                    else if(kind==u"escape")status=combat_action(combat,CombatAction::Escape,2);
                    else if(kind==u"quick")status=combat_action(combat,CombatAction::EscapeQuick);
                    else if(kind==u"flee")status=combat_action(combat,CombatAction::Move,2);
                    else if(kind==u"hold")status=combat_action(combat,CombatAction::Pass);
                    else {CombatActor *target=nullptr;int best=999;for(int j=0;j<state->count;++j){auto &e=state->actors[j];if(e.member!=255||(e.status!=CombatStatus::Active&&e.status!=CombatStatus::Sleeping))continue;int d=std::max(std::abs(int(e.position.x)-u->position.x),std::abs(int(e.position.y)-u->position.y));if(d<best||(d==best&&target&&e.id<target->id)){target=&e;best=d;}}
                        status=!target?combat_action(combat,CombatAction::Pass):best<=u->range?combat_action(combat,CombatAction::Attack,target->position.x,target->position.y):combat_action(combat,CombatAction::Move,target->position.x!=u->position.x?(target->position.x>u->position.x?0:1):(target->position.y>u->position.y?2:3));}
                    if(status!=CombatResult::Ok)return 7;
                }
            }else{
                if(kind==u"cbuse"){for(int i=0;i<100;++i){auto *a=current_combat_actor(combat);if(!a||a->member!=255)break;combat_action(combat,CombatAction::EnemyStep);}}
                Command cmd;cmd.kind=kind==u"dngAttack"?CommandKind::DungeonCommand:kind==u"dngForward"?CommandKind::DungeonCommand:kind==u"order"?CommandKind::NewOrder:kind==u"active"?CommandKind::SetActivePlayer:kind==u"view"?CommandKind::ViewGem:kind==u"afterView"?CommandKind::AfterGemView:kind==u"ignite"?CommandKind::Ignite:kind==u"board"?CommandKind::Board:kind==u"disembark"?CommandKind::Disembark:kind==u"cbuse"?CommandKind::UseItem:kind==u"mix"?CommandKind::Mix:kind==u"wish"?CommandKind::MakeWish:kind==u"fire"?CommandKind::Fire:kind==u"attack"?CommandKind::Attack:kind==u"rest"?CommandKind::Rest:kind==u"cast"?CommandKind::Cast:kind==u"look"?CommandKind::Look:kind==u"crystal"?CommandKind::CrystalBall:kind==u"coin"?CommandKind::DropCoin:kind==u"move"?CommandKind::Move:kind==u"sails"?CommandKind::YellSails:kind==u"toll"?CommandKind::TrollToll:kind==u"open"?CommandKind::Open:kind==u"jimmy"?CommandKind::Jimmy:kind==u"push"?CommandKind::Push:kind==u"get"?CommandKind::Get:kind==u"klimb"?CommandKind::Klimb:kind==u"use"?CommandKind::UseItem:CommandKind::Pass;cmd.direction=Direction(action["dir"].integer());cmd.has_direction=action.has("dir");cmd.reagent_mask=uint8_t(action["mask"].integer());cmd.text=action["text"].string.data();cmd.text_length=action["text"].string.size();cmd.hours=int16_t(action["hours"].integer());cmd.caster=int16_t(action["caster"].integer(-1));cmd.item=int16_t(action["item"].integer());cmd.member=action.has("member")?int16_t(action["member"].integer()):action["pay"].truth()?1:0;
                if(kind==u"dngAttack")cmd.item=int16_t(DungeonAction::Attack);
                const auto ar=execute_command(ctx,cmd);if(ar.status==CommandStatus::InvalidContext||ar.status==CommandStatus::CoreError||ar.status==CommandStatus::NeedsStorage){std::cerr<<"gameplay command status "<<int(ar.status)<<"\n";return 8;}
            }
            if(q.has("dungeon")){auto &d=step["dungeon"];d=Json::object();d["position"]=Json::object();auto &p=d["position"];p["dungeon"]=Json(dungeon->pos.dungeon);p["floor"]=Json(dungeon->pos.floor);p["x"]=Json(dungeon->pos.x);p["y"]=Json(dungeon->pos.y);const char *dirs[]={"north","east","south","west"};p["facing"]=Json(dirs[int(dungeon->pos.facing)]);d["cells"]=Json::array();for(auto cell:dungeon->cells)d["cells"].values.emplace_back(cell);}
            Json snapshot=q["state"];save::capture_core(g,t,snapshot);save::capture_gameplay(commands,outdoor,snapshot);save::capture_terrain(terrain,snapshot);
            if(has_npcs){step["npcs"]=Json::array();for(size_t i=0;i<actors->count;++i){auto &a=actors->actors[i];if(a.location!=g.position.map.location)continue;Json row=Json::array();for(int n:{int(a.schedule.slot),int(a.schedule.type),int(a.schedule.dialog),int(a.x),int(a.y),int(a.z)})row.values.emplace_back(n);Json ai=Json::array();for(auto n:a.schedule.ai)ai.values.emplace_back(n);row.values.push_back(ai);step["npcs"].values.push_back(row);}step["npcDead"]=snapshot["npcDead"];}
            if(q["activeInspect"].truth()){step["activeTiles"]=Json::array();for(auto &pos:q["inspectCoords"].values)step["activeTiles"].values.emplace_back(transport.tile_at(transport.context,int32_t(pos.at(0).integer()),int32_t(pos.at(1).integer())));}
            if(q["inspect"].truth()){step["tiles"]=Json::array();for(const auto &pos:q["inspectCoords"].values)step["tiles"].values.emplace_back(quest.tile_at(quest.context,int32_t(pos.at(0).integer()),int32_t(pos.at(1).integer())));}
            if(outdoor.has_chunk_origin){snapshot["chunkOrigin"]=Json::object();snapshot["chunkOrigin"]["x"]=Json(outdoor.chunk_x);snapshot["chunkOrigin"]["y"]=Json(outdoor.chunk_y);}snapshot["worldObjects"]=objects.values;std::string buffer;if(save::encode_json(snapshot,buffer)!=save::JsonError::None)return 10;Json decoded;if(save::parse_json(buffer,decoded)!=save::JsonError::None||save::restore_gameplay(decoded,commands,outdoor)!=save::Error::None)return 11;if(&action==&q["actions"].values.back()){auto loaded=std::make_unique<GameState>();TurnState loaded_turn;Json retained;std::string saved;if(save::save_state(g,t,snapshot,saved)!=save::Error::None||save::load_state(saved,*loaded,loaded_turn,retained)!=save::Error::None)return 13;Json recaptured=retained;save::capture_core(*loaded,loaded_turn,recaptured);if(save::write_json(retained)!=save::write_json(recaptured))return 14;WorldTerrain restored;OutdoorServices enemies;CommandState command;if(save::restore_terrain(retained,restored)!=save::Error::None||save::restore_gameplay(retained,command,enemies)!=save::Error::None)return 15;}step["state"]=std::move(snapshot);step["seed"]=Json(g.rng.get_seed());step["combat"]=combat_snapshot(combat,ctx.combat);result.values.push_back(std::move(step));
        }
        output<<save::write_json(result)<<'\n';
    }
}


