#include "openu5/transport.h"
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
using namespace openu5;
struct Hash{uint32_t h=2166136261u;void n(int64_t n){for(int i=0;i<4;i++)h=(h^((uint32_t(n)>>(i*8))&255))*16777619u;}void s(const std::string &s){n(s.size());for(unsigned char c:s)h=(h^c)*16777619u;}};
struct Owner{int overlay,base,near;struct Ship{int tile,hull,skiffs;};std::vector<Ship> ships;std::vector<std::pair<std::string,std::string>> events;};
int main(int argc,char **argv){if(argc!=2)return 2;std::ifstream in(argv[1]);int k,from,v,count=0;const int tiles[]={5,0x110,0x11b,0x124,0x128,0x24};std::vector<uint8_t> terrain(65536,5);
 while(in>>k>>from>>v){Owner owner{tiles[k],v&1?106:5,v&2?1:5,{},{}};if(k==3&&(v&4))owner.ships.push_back({0x124,7,2});GameState g;TurnState t;TravelState travel;CommandState commands;WorldData world;world.overworld=terrain.data();world.overworld_size=terrain.size();CommandContext c{g,t,travel,commands,world};g.rng.seed(k*901+from*31+v);g.position.xy={20,20};g.time={139,1,1,5,59};g.party.party_size=g.party.character_count=1;g.party.active_character=255;auto &r=g.party.characters[0];r.status='G';r.current_hp=r.max_hp=100;r.ring=255;r.party_status=0;g.food=100;g.ship_hull=99;g.ship_skiffs=v%3;g.magic_carpets=v%2;g.transport=transport_mode(from);t.transport_tile=from;t.prev_hour=5;t.time_spell=v&4?'Q':0;t.spell_turns=255;t.wind=2;
 TransportServices s;s.context=&owner;s.tile_at=[](void *p,int32_t x,int32_t y)->int32_t{auto &o=*static_cast<Owner*>(p);return x==20&&y==20?(!o.ships.empty()?o.ships[0].tile:o.overlay<0?o.base:o.overlay):o.near;};s.ship_at=[](void *p,WorldPosition,int32_t &h,int32_t &s){auto &o=*static_cast<Owner*>(p);if(o.ships.empty())return false;h=o.ships[0].hull;s=o.ships[0].skiffs;return true;};s.reserve=[](void *,bool){return true;};s.remove_boarded=[](void *p,WorldPosition,int32_t){auto &o=*static_cast<Owner*>(p);if(o.ships.empty())o.overlay=-1;else o.ships.erase(o.ships.begin());};s.drop=[](void *p,WorldPosition,int32_t tile){static_cast<Owner*>(p)->overlay=tile;};s.park_ship=[](void *p,WorldPosition,int32_t tile,int32_t h,int32_t s){static_cast<Owner*>(p)->ships.push_back({int(tile),int(h),int(s)});};c.transport_services=&s;c.events={&owner,[](void *p,const GameEvent &e){static_cast<Owner*>(p)->events.emplace_back(e.kind==GameEventKind::Message?"message":e.kind==GameEventKind::Sfx?"sfx":"map-changed",e.text?e.text:"");}};
 for(int a=0;a<4;++a){owner.events.clear();Command cmd;cmd.kind=a%2?CommandKind::Disembark:CommandKind::Board;execute_command(c,cmd);Hash h;for(int n:{int(g.rng.get_seed()),t.transport_tile,int(g.transport),int(g.ship_hull),int(g.ship_skiffs),int(g.magic_carpets),int(g.turns_since_start),int(g.time.hour),int(g.time.minute),t.prev_hour,int(g.food),t.wind,t.wind_drift_counter,commands.outdoor_phases.mount,commands.outdoor_phases.quickness,owner.overlay,int(owner.ships.size())})h.n(n);for(auto o:owner.ships){h.n(o.tile);h.n(o.hull);h.n(o.skiffs);}for(auto &e:owner.events){h.s(e.first);h.s(e.second);}uint32_t expected;in>>expected;if(h.h!=expected){std::cerr<<"transport flow mismatch "<<k<<" "<<from<<" "<<v<<" action "<<a<<"\n";return 1;}++count;}}
 std::cout<<count<<" transport orchestration snapshots passed\n";return count?0:2;
}
