#include "openu5/intro_view.h"
#include <algorithm>
#include <cstring>
namespace openu5 {namespace {constexpr int8_t dx[4]={0,1,0,-1},dy[4]={-1,0,1,0};constexpr const char*titles[]={"The Summoning","The Journey","The Arrival","The Welcoming"};}
const char*IntroViewPlayer::scene_title(uint8_t s){return s<4?titles[s]:"The View";}
bool IntroViewPlayer::bind(IntroViewData d){if(!d.maps||d.map_bytes!=4U*kIntroViewCells||!d.script||d.script_bytes<2)return false;data_=d;reset();return true;}
void IntroViewPlayer::reset(){pc_=loop_pc_=0;frames_left_=phase_total_=0;scene_=loop_count_=phase_slot_=moon_col_=moon_row_=0;curtain_left_=curtain_right_=9;curtain_toggle_=false;phase_=Phase::None;cycle_=0;std::memset(terrain_,0,sizeof(terrain_));for(auto&a:actors_)a={};}
bool IntroViewPlayer::schedule(Phase p,uint16_t n,uint8_t s){phase_=p;frames_left_=phase_total_=n;phase_slot_=s;return n!=0;}
void IntroViewPlayer::finish_phase(){if(phase_==Phase::MoonRise){terrain_[moon_row_*19+moon_col_]=0xdc;schedule(Phase::Tick,2);return;}if(phase_==Phase::MoonFall){schedule(Phase::Tick,2);return;}if(phase_==Phase::DissolveIn&&phase_slot_<32)actors_[phase_slot_].active=true;phase_=Phase::None;frames_left_=phase_total_=0;}
void IntroViewPlayer::emit(IntroViewFrame&o,uint16_t step){o={};o.scene=scene_;o.cycle=cycle_;if(curtain_toggle_){if(curtain_left_)--curtain_left_;if(curtain_right_<18)++curtain_right_;}curtain_toggle_=!curtain_toggle_;o.curtain_left=curtain_left_;o.curtain_right=curtain_right_;std::copy_n(terrain_,kIntroViewCells,o.terrain);for(int i=0;i<kIntroViewCells;++i)o.tiles[i]=terrain_[i];for(const auto&a:actors_)if(a.active&&a.col<19&&a.row<4)o.tiles[a.row*19+a.col]=uint16_t(0x100U+a.tile);for(int r=0;r<4;++r)for(int c=0;c<19;++c)if(c<curtain_left_||c>curtain_right_)o.tiles[r*19+c]=0xffffU;if((phase_==Phase::DissolveIn||phase_==Phase::DissolveOut)&&phase_slot_<32){const auto&a=actors_[phase_slot_];o.effect=IntroViewEffect::Dissolve;o.effect_col=a.col;o.effect_row=a.row;o.effect_tile=uint16_t(0x100U+a.tile);o.effect_shown=uint16_t((phase_==Phase::DissolveIn?step+1U:phase_total_-step-1U)*256U/phase_total_);}else if(phase_==Phase::MoonRise||phase_==Phase::MoonFall){o.effect=IntroViewEffect::Moongate;o.effect_col=moon_col_;o.effect_row=moon_row_;o.effect_tile=0xdc;o.effect_step=uint8_t(phase_==Phase::MoonRise?step+1U:phase_total_-step-1U);}else if(phase_==Phase::Summon&&step<5){o.effect=IntroViewEffect::Beam;o.effect_step=uint8_t(step);}o.thunder=phase_==Phase::Tick&&phase_total_==2&&step==0;o.chime=(phase_==Phase::MoonRise||phase_==Phase::MoonFall)&&(step==0||step==4);o.summon=phase_==Phase::Summon&&step==5;}
bool IntroViewPlayer::advance(IntroViewFrame&o){if(!data_.maps||!data_.script)return false;for(size_t guard=0;guard<4096;++guard){if(frames_left_){const uint16_t step=uint16_t(phase_total_-frames_left_);emit(o,step);--frames_left_;if(!frames_left_)finish_phase();return true;}if(pc_>=data_.script_bytes)return false;const uint8_t op=data_.script[pc_];auto a=[&](size_t i){return pc_+1+i<data_.script_bytes?data_.script[pc_+1+i]:uint8_t(0);};switch(op){case 0:{auto&v=actors_[a(0)&31];v={a(1),a(2),a(3),true};pc_+=5;break;}case 1:actors_[a(0)&31].active=false;pc_+=2;break;case 2:{auto&v=actors_[a(0)&31];const uint8_t d=uint8_t(a(1)&3);v.col=uint8_t(int(v.col)+dx[d]);v.row=uint8_t(int(v.row)+dy[d]);pc_+=3;break;}case 3:{auto n=a(0);pc_+=2;schedule(Phase::Tick,n);break;}case 4:moon_col_=a(0);moon_row_=a(1);pc_+=3;schedule(Phase::MoonRise,15);break;case 5:if(moon_col_<19&&moon_row_<4)terrain_[moon_row_*19+moon_col_]=5;++pc_;schedule(Phase::MoonFall,15);break;case 6:scene_=uint8_t(a(0)&3);std::copy_n(data_.maps+size_t(scene_)*kIntroViewCells,kIntroViewCells,terrain_);curtain_left_=curtain_right_=9;curtain_toggle_=false;pc_+=2;break;case 7:{const uint8_t s=uint8_t(a(0)&31);actors_[s].active=false;pc_+=2;schedule(Phase::DissolveIn,8,s);break;}case 8:{const uint8_t s=uint8_t(a(0)&31);actors_[s].active=false;pc_+=2;schedule(Phase::DissolveOut,8,s);break;}case 9:pc_=0;++cycle_;break;case 10:if(a(1)<19&&a(2)<4)terrain_[a(2)*19+a(1)]=a(0);pc_+=4;break;case 11:pc_+=3;schedule(Phase::Summon,9,uint8_t(a(1)&31));break;case 12:for(auto&v:actors_)v={};++pc_;break;case 13:{auto&v=actors_[a(0)&31];const uint8_t d=uint8_t(a(1)&3);v.col=uint8_t(int(v.col)+dx[d]);v.row=uint8_t(int(v.row)+dy[d]);pc_+=3;schedule(Phase::Tick,7);break;}case 14:loop_count_=a(0);loop_pc_=pc_+2;pc_+=2;break;case 15:if(loop_count_>1){--loop_count_;pc_=loop_pc_;}else{loop_count_=0;++pc_;}break;default:++pc_;break;}}return false;}
}
