#include "openu5/system_menu.h"
#include <algorithm>
#include <cstdio>
#include <cstring>
namespace openu5 {namespace {bool up(const UiAction&a){return a.kind==UiActionKind::Previous||(a.kind==UiActionKind::Direction&&a.direction==Direction::North);}bool down(const UiAction&a){return a.kind==UiActionKind::Next||(a.kind==UiActionKind::Direction&&a.direction==Direction::South);}bool left(const UiAction&a){return a.kind==UiActionKind::Direction&&a.direction==Direction::West;}bool right(const UiAction&a){return a.kind==UiActionKind::Direction&&a.direction==Direction::East;}}
void SystemMenuSession::open(const FrontendSettings&s,const FrontendSaveSlot(&slots)[2]){active_=true;page_=Page::Root;cursor_=settings_cursor_=0;settings_=s;saves_[0]=slots[0];saves_[1]=slots[1];pending_={};}
bool SystemMenuSession::handle(const UiAction&a){if(!active_)return false;if(a.kind==UiActionKind::Cancel||a.kind==UiActionKind::Back){if(page_==Page::Root){pending_.kind=SystemMenuIntentKind::Resume;close();}else{if(page_==Page::Settings){pending_.kind=SystemMenuIntentKind::PersistSettings;pending_.settings=settings_;}page_=Page::Root;cursor_=0;}return true;}if(page_==Page::Root){const uint8_t count=settings_.developer_tools_visible?6U:5U;if(up(a))cursor_=uint8_t((cursor_+count-1)%count);else if(down(a))cursor_=uint8_t((cursor_+1)%count);else if(a.kind==UiActionKind::Confirm){switch(cursor_){case 0:pending_.kind=SystemMenuIntentKind::Resume;close();break;case 1:pending_.kind=SystemMenuIntentKind::Save;break;case 2:page_=Page::Load;cursor_=0;break;case 3:page_=Page::Settings;settings_cursor_=0;break;case 4:if(settings_.developer_tools_visible){pending_.kind=SystemMenuIntentKind::OpenDeveloper;close();}else{pending_.kind=SystemMenuIntentKind::ReturnToTitle;close();}break;case 5:pending_.kind=SystemMenuIntentKind::ReturnToTitle;close();break;}}else return false;return true;}if(page_==Page::Load){if(up(a))cursor_=uint8_t((cursor_+2)%3);else if(down(a))cursor_=uint8_t((cursor_+1)%3);else if(a.kind==UiActionKind::Confirm){if(cursor_==0)pending_.kind=SystemMenuIntentKind::LoadLatest;else if(saves_[cursor_-1].valid){pending_.kind=SystemMenuIntentKind::LoadSlot;pending_.slot=int8_t(cursor_-1);}}else return false;return true;}if(up(a))settings_cursor_=uint8_t((settings_cursor_+kSettingsRowCount-1)%kSettingsRowCount);else if(down(a))settings_cursor_=uint8_t((settings_cursor_+1)%kSettingsRowCount);else if(left(a)||right(a)||a.kind==UiActionKind::Confirm){const int d=left(a)?-1:1;switch(settings_cursor_){case kBrightnessRow:settings_.brightness=uint8_t(std::clamp(int(settings_.brightness)+d*10,10,100));break;case kMovementRow:settings_.movement_mode=!settings_.movement_mode;break;case kTrackballRow:settings_.trackball_responsiveness=uint16_t(std::clamp(int(settings_.trackball_responsiveness)+d*25,25,300));break;case kTextSizeRow:settings_.ui_size=uint8_t((int(settings_.ui_size)+d+3)%3);break;
// A3-01. Music Volume is kept, not edited, while no music is available: the
// row says so and the stored preference survives for a later music pack.
case kSfxVolumeRow:settings_.sound_volume=step_volume(settings_.sound_volume,d);volume_edits_|=kSfxVolumeEdited;break;case kMusicVolumeRow:if(music_availability_==MusicAvailability::Available){settings_.music_volume=step_volume(settings_.music_volume,d);volume_edits_|=kMusicVolumeEdited;}break;case kDeveloperRow:settings_.developer_tools_visible=!settings_.developer_tools_visible;break;}}else return false;return true;}
SystemMenuIntent SystemMenuSession::take_intent(){auto i=pending_;pending_={};return i;}
FrontendView SystemMenuSession::view()const{FrontendView v{};v.kind=page_==Page::Settings?FrontendViewKind::Settings:FrontendViewKind::SystemMenu;v.title="System Menu";static char d[8][96]{};if(page_==Page::Root){for(auto s:{"Resume","Save","Load / Save Management","Settings"})v.lines[v.line_count++]=s;if(settings_.developer_tools_visible)v.lines[v.line_count++]="Developer / Debug";v.lines[v.line_count++]="Return to Title";v.selected_line=cursor_;v.footer="Alt+M or Mic: resume";}else if(page_==Page::Load){v.title="Load / Save Management";v.lines[v.line_count++]="Continue Latest";for(int i=0;i<2;++i){std::snprintf(d[i],96,"Generation %d: %s",i+1,saves_[i].valid?(saves_[i].name[0]?saves_[i].name:"valid"):saves_[i].present?"corrupt":"empty");v.lines[v.line_count++]=d[i];}v.selected_line=cursor_;v.footer="Enter loads; Mic returns";}else{static const char*ui_sizes[]={"Small","Medium","Large"};v.title="Settings";std::snprintf(d[0],96,"Brightness: %u%%",settings_.brightness);std::snprintf(d[1],96,"Movement default: %s",settings_.movement_mode?"On":"Off");std::snprintf(d[2],96,"Trackball: %u%%",unsigned(settings_.trackball_responsiveness));std::snprintf(d[3],96,"Text / UI: %s",ui_sizes[std::min<unsigned>(settings_.ui_size,2)]);format_sfx_volume_row(d[4],96,settings_.sound_volume,sfx_muted_);format_music_volume_row(d[5],96,settings_.music_volume,music_availability_,music_muted_);std::snprintf(d[6],96,"Developer: %s",settings_.developer_tools_visible?"Visible":"Hidden");for(int i=0;i<kSettingsRowCount;++i)v.lines[v.line_count++]=d[i];v.selected_line=settings_cursor_;const char*why=settings_cursor_==kMusicVolumeRow?music_unavailable_reason(music_availability_):nullptr;v.footer=why?why:"Left/right changes; Mic returns";}return v;}
}
