#include "openu5/system_menu.h"
#include <algorithm>
#include <cstdio>
#include <cstring>
namespace openu5 {namespace {bool up(const UiAction&a){return a.kind==UiActionKind::Previous||(a.kind==UiActionKind::Direction&&a.direction==Direction::North);}bool down(const UiAction&a){return a.kind==UiActionKind::Next||(a.kind==UiActionKind::Direction&&a.direction==Direction::South);}bool left(const UiAction&a){return a.kind==UiActionKind::Direction&&a.direction==Direction::West;}bool right(const UiAction&a){return a.kind==UiActionKind::Direction&&a.direction==Direction::East;}}
void SystemMenuSession::open(const FrontendSettings&s,const FrontendSaveSlot(&slots)[2]){active_=true;page_=Page::Root;cursor_=settings_cursor_=0;settings_=s;saves_[0]=slots[0];saves_[1]=slots[1];pending_={};notice_[0]=0;}
void SystemMenuSession::set_notice(const char*text){std::snprintf(notice_,sizeof(notice_),"%s",text?text:"");}
bool SystemMenuSession::handle(const UiAction&a){if(!active_)return false;notice_[0]=0;if(a.kind==UiActionKind::Cancel||a.kind==UiActionKind::Back){if(page_==Page::Root){pending_.kind=SystemMenuIntentKind::Resume;close();}else{if(page_==Page::Settings){pending_.kind=SystemMenuIntentKind::PersistSettings;pending_.settings=settings_;}page_=Page::Root;cursor_=0;}return true;}if(page_==Page::Root){const uint8_t count=settings_.developer_tools_visible?6U:5U;if(up(a))cursor_=uint8_t((cursor_+count-1)%count);else if(down(a))cursor_=uint8_t((cursor_+1)%count);else if(a.kind==UiActionKind::Confirm){switch(cursor_){case 0:pending_.kind=SystemMenuIntentKind::Resume;close();break;case 1:pending_.kind=SystemMenuIntentKind::Save;break;case 2:page_=Page::Load;cursor_=0;break;case 3:page_=Page::Settings;settings_cursor_=0;break;case 4:if(settings_.developer_tools_visible){pending_.kind=SystemMenuIntentKind::OpenDeveloper;close();}else{pending_.kind=SystemMenuIntentKind::ReturnToTitle;close();}break;case 5:pending_.kind=SystemMenuIntentKind::ReturnToTitle;close();break;}}else return false;return true;}if(page_==Page::Load){
// Alpha 4 UI Batch 2 (ALPHA4_UI.md section 2.3): row 0 the Latest save (Continue
// Latest, with its fallback), row 1 its Backup (that generation alone).
if(up(a)||down(a))cursor_^=1;else if(a.kind==UiActionKind::Confirm){const auto l=order_saves(saves_);if(cursor_==0)pending_.kind=SystemMenuIntentKind::LoadLatest;else if(l.backup>=0&&saves_[l.backup].valid){pending_.kind=SystemMenuIntentKind::LoadSlot;pending_.slot=l.backup;}else set_notice(l.backup<0?"No backup save yet":"That backup is damaged and cannot load");}else return false;return true;}if(up(a))settings_cursor_=uint8_t((settings_cursor_+kSettingsRowCount-1)%kSettingsRowCount);else if(down(a))settings_cursor_=uint8_t((settings_cursor_+1)%kSettingsRowCount);else if(left(a)||right(a)||a.kind==UiActionKind::Confirm){const int d=left(a)?-1:1;switch(settings_cursor_){case kBrightnessRow:settings_.brightness=uint8_t(std::clamp(int(settings_.brightness)+d*10,10,100));break;case kMovementRow:settings_.movement_mode=!settings_.movement_mode;break;case kTrackballRow:settings_.trackball_responsiveness=uint16_t(std::clamp(int(settings_.trackball_responsiveness)+d*25,25,300));break;case kTextSizeRow:settings_.ui_size=uint8_t((int(settings_.ui_size)+d+3)%3);break;
// A3-01. Music Volume is kept, not edited, while no music is available: the
// row says so and the stored preference survives for a later music pack.
case kSfxVolumeRow:settings_.sound_volume=step_volume(settings_.sound_volume,d);volume_edits_|=kSfxVolumeEdited;break;case kMusicVolumeRow:if(music_availability_==MusicAvailability::Available){settings_.music_volume=step_volume(settings_.music_volume,d);volume_edits_|=kMusicVolumeEdited;}break;case kDeveloperRow:settings_.developer_tools_visible=!settings_.developer_tools_visible;break;}}else return false;return true;}
SystemMenuIntent SystemMenuSession::take_intent(){auto i=pending_;pending_={};return i;}
FrontendView SystemMenuSession::view()const{FrontendView v{};v.kind=page_==Page::Settings?FrontendViewKind::Settings:FrontendViewKind::SystemMenu;v.title="System Menu";static char d[8][96]{};if(page_==Page::Root){for(auto s:{"Resume","Save Game","Load Game","Settings"})v.lines[v.line_count++]=s;if(settings_.developer_tools_visible)v.lines[v.line_count++]="Developer / Debug";v.lines[v.line_count++]="Return to Title";v.selected_line=cursor_;
 // Alpha 4 UI Batch 2: the selected row says what it will do.
 v.footer=notice_[0]?notice_:cursor_==1?"Saves now; the previous save becomes the backup":cursor_==2?"The latest save and its backup":size_t(cursor_)+1==v.line_count?"Unsaved progress will be lost":"Alt+M or Mic: resume";}else if(page_==Page::Load){v.title="Load Game";v.subtitle="Each save keeps the one before as a backup";format_save_row(d[0],96,saves_,true);format_save_row(d[1],96,saves_,false);v.lines[v.line_count++]=d[0];v.lines[v.line_count++]=d[1];v.selected_line=cursor_;format_save_detail(d[2],96,saves_,cursor_==0);v.footer=notice_[0]?notice_:d[2];}else{static const char*ui_sizes[]={"Small","Medium","Large"};v.title="Settings";std::snprintf(d[0],96,"Brightness: %u%%",settings_.brightness);std::snprintf(d[1],96,"Movement default: %s",settings_.movement_mode?"On":"Off");std::snprintf(d[2],96,"Trackball: %u%%",unsigned(settings_.trackball_responsiveness));std::snprintf(d[3],96,"Text / UI: %s",ui_sizes[std::min<unsigned>(settings_.ui_size,2)]);format_sfx_volume_row(d[4],96,settings_.sound_volume,sfx_muted_);format_music_volume_row(d[5],96,settings_.music_volume,music_availability_,music_muted_);std::snprintf(d[6],96,"Developer: %s",settings_.developer_tools_visible?"Visible":"Hidden");for(int i=0;i<kSettingsRowCount;++i)v.lines[v.line_count++]=d[i];v.selected_line=settings_cursor_;const char*why=settings_cursor_==kMusicVolumeRow?music_unavailable_reason(music_availability_):nullptr;v.footer=why?why:"Left/right changes; Mic returns";}return v;}
}
