import {NpcManager} from '../../../game/src/core/npc/manager.js';
import {DungeonState} from '../../../game/src/core/dungeon/dungeon.js';
import {castSpell,applyMani,applyVasMani,applyCure,applyAwaken,applyResurrect,inWisPeerText} from '../../../game/src/core/magic/cast.js';
import {buildSpellDefs} from '../../../game/src/core/magic/spells.js';
import {readScroll,windForDirection} from '../../../game/src/core/useScroll.js';
import {scrollCeremonyIndex,potionCeremonyIndex,castCeremonyIndexOrNull,VAS_REL_POR_SPELL_INDEX,VAS_REL_POR_PHASE_CEREMONY_INDEX} from '../../../game/src/core/magic/ceremony.js';
import {rerollPotionColor,applyPotionEffect,applyPotionCombatSync} from '../../../game/src/core/usePotion.js';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {isDeepStrictEqual} from 'node:util';
import {Game} from '../../../game/src/core/game.js';
import {buildEnemyDefs} from '../../../game/src/core/combat/enemies.js';
import {transportMode} from '../../../game/src/core/world/transport.js';
import {instalaDsStrings} from '../../../game/src/core/data/ds-strings.js';
import {tileInfo} from '../../../game/src/core/tiles.js';
import {DoorManager} from '../../../game/src/core/world/doors.js';
const dir='native/core/build-gameplay';mkdirSync(dir,{recursive:true});
const data=JSON.parse(readFileSync('game/assets/data.json','utf8'));
instalaDsStrings(JSON.parse(readFileSync('game/assets/ds-strings.json','utf8')));
data.signs=JSON.parse(readFileSync('game/assets/signs.json','utf8'));
data.look2=JSON.parse(readFileSync('game/assets/look2.json','utf8'));
const real=JSON.parse(readFileSync('game/assets/maps/overworld.json','utf8'));
const underworld=JSON.parse(readFileSync('game/assets/maps/underworld.json','utf8'));
const realSmallMaps=JSON.parse(readFileSync('game/assets/maps/smallmaps.json','utf8'));
writeFileSync(dir+'/overworld.bin',Buffer.from(real.flat()));
const enemyDefs=buildEnemyDefs(data,JSON.parse(readFileSync('game/src/core/data/AdditionalEnemyFlags.json','utf8'))).map(d=>({...d,nativeMask:(data.enemyFlags[d.index][0]<<8)|data.enemyFlags[d.index][1]}));
const resources={shardSpawns:data.shardSpawns,karma:JSON.parse(readFileSync("game/assets/ds-strings.json","utf8"))["KARMA.DAT"],descriptions:Array.from({length:512},(_,i)=>{const t=tileInfo(i);return data.look2?.[i]||(t.description.trim()?t.description:t.name);}),enemyDefs,combatMaps:JSON.parse(readFileSync('game/assets/maps/combatmaps.json','utf8')).slice(0,16),attackValues:data.attackValues,attackRangeValues:data.attackRangeValues,defenseValues:data.defenseValues,spellAttackRange:data.spellAttackRange};
writeFileSync(dir+'/assets.json',JSON.stringify(resources));
function initial():any{return {version:1,characters:[{name:'Avatar',gender:11,class:'A',status:'G',strength:99,dexterity:30,intelligence:20,currentMp:0,currentHp:30000,maxHp:30000,exp:0,level:1,monthsAtInn:0,helmet:255,armor:255,weapon:38,shield:255,ring:255,amulet:255,partyStatus:0}],partySize:1,activeCharacter:0,food:100,gold:500,keys:0,gems:0,torches:0,skullKeys:0,magicCarpets:1,karma:50,turnsSinceStart:0,torchTurns:0,transport:'foot',transportTile:28,time:{year:139,month:4,day:5,hour:0,minute:0},position:{location:0,floor:0,x:10,y:10},equipmentQuantities:Array(48).fill(0),scrollQuantities:Array(8).fill(0),potionQuantities:Array(8).fill(0),spellQuantities:Array(48).fill(0),reagentQuantities:Array(8).fill(0),npcDead:Array.from({length:32},()=>Array(32).fill(false)),npcMet:Array.from({length:32},()=>Array(32).fill(false)),questFlags:{},shards:{falsehood:false,hatred:false,cowardice:false},lbArtifacts:{amulet:false,crown:false,sceptre:false},specialItems:{woodenBox:false},worldObjects:[],overworldEnemies:[],shipHull:99,shipSkiffs:2,wind:2,windDriftCtr:0,sailDir:0,hmsCapeToggle:0};}
const fields=['skullKeys','grapple','position','time','turnsSinceStart','characters','partySize','activeCharacter','food','gold','karma','keys','gems','torches','torchTurns','potionQuantities','scrollQuantities','transport','transportTile','shipHull','shipSkiffs','magicCarpets','overworldEnemies','worldObjects','equipmentQuantities','questFlags','spellQuantities','reagentQuantities','wornCrown'];
function projection(s:any){return {...Object.fromEntries(fields.map(k=>[k,s[k]])),grapple:!!s.grapple,wornCrown:!!s.wornCrown,lightSpellMins:s.lightSpellMins??0,timeSpell:s.timeSpell??null,timeSpellTurns:s.timeSpellTurns??null,mapOverrides:s.mapOverrides??{},chunkOrigin:s.chunkOrigin??null,wind:s.wind??0,windDriftCtr:s.windDriftCtr??0,sailDir:s.sailDir??0,hmsCapeToggle:s.hmsCapeToggle??0};}
function battle(c:any){return c?{active:true,seed:c.finalSeed,map:c.map.index,tiles:c.mapTiles.flat(),current:c.currentActor?.id??-1,actors:c.combatants.map((a:any)=>[a.id,a.charIdx??255,a.enemyDef?.index??-1,a.x,a.y,a.hp,a.maxHp,a.str,a.dex,a.int,a.defense,a.attack,a.attackRange,['active','dead','fled','sleeping','charmed','absorbed'].indexOf(a.status),a.speed,a.counter,!!a.sleeping,!!a.invisible,!!a.charmed,a.renderTile??-1])}:{active:false};}
function event(e:any){return {kind:e.kind,text:e.text??e.sfx?.id??'',...(e.ceremony!==undefined?{ceremony:e.ceremony}:{}),...(e.refuge?{refuge:e.refuge}:{}),...(e.signLines?{sign:true,raw:e.signRaw??[]}:{}),...(e.projectileFx?{projectile:e.projectileFx}:{}),...(e.frames!==undefined?{frames:e.frames}:{}),...(e.zodiacView?{zodiac:e.zodiacView}:{}),...(e.gemFromCrystalBall?{crystal:true}:{}),...(e.toll!==undefined?{toll:e.toll}:{}),...(e.poisonTick?{slots:e.poisonTick.slots}:{}),...(e.trollSneak?{beats:e.trollSneak.beats.map((b:any)=>[b.message??b.append??'',b.pauseUnits??-1,b.append!==undefined])}:{})};}
const inputs:any[]=[],expected:any[]=[],coverage:Record<string,number>={};
function add(seed:number,tile:number,edit:(s:any)=>void,realMap=false,finish='flee',scenario:any={}){
 const s=initial();s.moonstones=[];edit(s);const q:any={seed,tile,real:realMap,...scenario,state:structuredClone(s),actions:[]};
 const terrain=realMap?structuredClone(real):Array.from({length:256},()=>Array(256).fill(tile));
 if(scenario.small)for(let y=0;y<32;y++)for(let x=0;x<32;x++)terrain[y][x]=scenario.small[y][x];
 for(const [x,y,t] of scenario.edits??[])terrain[y][x]=t;
 const npcs=scenario.npcs?new NpcManager({[s.position.location]:scenario.npcs}):undefined;
 const g:any=new Game({} as any,{overworld:terrain,underworld:terrain,smallMaps:new Map(s.position.location?[[s.position.location,{id:s.position.location,name:'',floors:[{z:s.position.floor,tiles:terrain.slice(0,32).map((row:any)=>row.slice(0,32))}]}]]:[])},data,s,{npcManager:npcs,doors:new DoorManager(),combatResources:{...resources,combatMaps:Object.fromEntries([...resources.combatMaps,...(scenario.room?[scenario.room]:[])].map((m:any)=>[m.index,m]))}});
 g.reseed(seed);
 if(scenario.dungeon){const d=scenario.dungeon;g.dungeonState=new DungeonState([{location:d.location,name:'Test',floors:Array.from({length:8},(_,f)=>Array.from({length:8},(_,y)=>Array.from({length:8},(_,x)=>({type:d.cells[f*64+y*8+x]>>4,sub:d.cells[f*64+y*8+x]&15}))))}],{dungeon:d.location,floor:3,x:3,y:3,facing:'north'},g.liveRng);}
 if(scenario.dungeon?.wanderer)Object.assign(g.dungeonState.wanderer,{type:scenario.dungeon.wanderer,x:3,y:2,floor:3});
 const steps:any[]=[];
 const act=(a:any)=>{q.actions.push(a);let ev:any[]=[],ce:any[]=[];
   const rng:any={randRange:(lo:number,hi:number)=>g.rand(lo,hi),rand30:()=>Math.max(1,g.rand(0,60)>>1)};
   const msg=(text:string)=>{if(text)ev.push({kind:'message',text});};
   const reveal=()=>ev.push({kind:'map-reveal',frames:20});
   // CAST2:0x0000 -- the jingle+viewport inversion every magic mouth performs.
   // Index/gate tables come from game/src/core/magic/ceremony.ts, which derives
   // the jump tables handler by handler; `null` = this mouth has no ceremony.
   const cue=(index:number|null|undefined)=>{if(index===null||index===undefined)return;ev.push({kind:'magic-ceremony',ceremony:index});};
   if(a.kind==='mix'){if(a.hours>0){const selected=Array.from({length:8},(_,i)=>i).filter(i=>a.mask&(1<<i));if(!selected.length)msg('Nothing to mix!');else if(selected.some(i=>s.reagentQuantities[i]<a.hours))msg('Insufficient reagents!');else{msg('Mixing...');ev.push(...g.mixReagents(buildSpellDefs(JSON.parse(readFileSync('game/src/core/data/MagicDefinitions.json','utf8')))[a.item],selected,a.hours));}}}
   else if(a.kind==='cbuse'){
     const cb=g.combat;if(cb){for(let i=0;i<100&&cb.currentUnit?.kind!=='player';i++){if(!cb.currentUnit)break;ce.push(...cb.tickEnemyTurnStep());}const u=cb.currentUnit;if(u?.kind==='player'){if(a.item>=16){if(a.item===16||a.item===32){msg(a.item===16?'Carpet':'Spyglass');msg('Not here!');}else if(a.item===17){if(s.skullKeys>0)s.skullKeys--;msg('Skull Key');}else if(a.item>=21&&a.item<=28){msg('Moonstone');msg('cannot be buried here!');}else if(a.item===34){msg('Sextant');msg('Only outdoors!');}else if(a.item===20){const n=cb.sceptreDissolveFields();msg('Sceptre');msg('Wielding the Sceptre of Lord British...');if(!n)msg('No effect!');}else{const names:any={18:'useAmulet',19:'useCrown',33:'useHmsCape',35:'usePocketWatch',36:'useBlackBadge',37:'useWoodenBox'};if(names[a.item])ev.push(...g[names[a.item]]());else ev.push(...g.useShard(['falsehood','hatred','cowardice'][a.item-29]));}ce.push(...cb.playerCast(null,null));}
       else if(a.item>=8){const color=a.item-8,rec=s.characters[u.charIdx];if(s.potionQuantities[color]>0)s.potionQuantities[color]--;msg('Potion');cue(potionCeremonyIndex(color));const out=applyPotionEffect(rec,rerollPotionColor(color,cb.rng),cb.rng,128);msg(out.message);applyPotionCombatSync(u,rec.currentHp,rec.status,out.effectiveColor,out.ok);ce.push(...cb.playerCast(null,null));}else{if(s.scrollQuantities[a.item]>0)s.scrollQuantities[a.item]--;msg('Scroll');const r=readScroll(s,a.item,128);r.messages.forEach(msg);if(a.item!==4)cue(scrollCeremonyIndex(a.item));ce.push(...cb.playerCast(r.followup.kind==='summonDaemon'?{kind:'summonDaemon',alwaysAlly:true}:null,null));}}}
   }else if(a.kind==='cast'){
     const r=castSpell(s,s.characters[a.caster],buildSpellDefs(JSON.parse(readFileSync('game/src/core/data/MagicDefinitions.json','utf8')))[a.item]!,{location:g.dungeonState?.pos.dungeon??s.position.location,inCombat:false},rng);msg(r.message);if(!r.ok&&r.consumed)msg('Failed!');
     // 41 of the 48 (C)ast handlers reach CAST2:0x0000 with their CIRCLE; the
     // weapon-spell and line-fan families do not (SPELLS_WITHOUT_CEREMONY), and
     // Vas Rel Por (46) fires its own literal-8 ceremony only after the phase
     // key (CAST.OVL 0x0cf0) passes -- modelled below in the 'gateTravel'
     // branch, not here (Y-33, native/targets/tdeck/GAMEPLAY_INTEGRATION_AUDIT.md).
     if(r.ok&&a.item!==VAS_REL_POR_SPELL_INDEX)cue(castCeremonyIndexOrNull(a.item));
     const f=r.effect,target=s.characters[a.member];if(f){
       if(g.dungeonState){if(f.kind==='fieldWall')ev.push(...g.applyDungeonFieldWall(f.fieldTile));else if(f.kind==='dispelField')ev.push(...g.applyAnGravDispel());else if(f.kind==='disarmOrOpen')ev.push(...g.applyAnSanctOpenChest());else if(f.kind==='dungeonAscend')ev.push(...g.dungeonMagicChangeLevel(-1));else if(f.kind==='dungeonDescend')ev.push(...g.dungeonMagicChangeLevel(1));else ev.push(...g.dungeonSpellTurn());}
       if(['healTarget','cure','awaken','resurrect'].includes(f.kind)&&target){const ok=f.kind==='healTarget'?(f.mode==='full'?applyVasMani(target):applyMani(target,rng)>0):f.kind==='cure'?applyCure(target):f.kind==='awaken'?applyAwaken(target):applyResurrect(target,s.karma);msg(ok?'Success!':'Failed!');}
       else if(f.kind==='peer')msg(inWisPeerText(s.position.x,s.position.y));
       else if(f.kind==='deathVision')reveal();
       else if(!scenario.dungeon&&(f.kind==='sealDoor'||f.kind==='disarmOrOpen')){if(a.dir===undefined)msg('Cancelled.');else ev.push(...(f.kind==='sealDoor'?g.applyDoorSpell(f,['north','south','east','west'][a.dir]):g.applyUnlockSpell(['north','south','east','west'][a.dir])));}
       else if(f.kind==='gateTravel'){if((s.transportTile&240)!==32&&a.hours>=0&&a.hours<=7)cue(VAS_REL_POR_PHASE_CEREMONY_INDEX);if((s.transportTile&240)===32||a.hours<0||a.hours>7||!g.moonstoneTeleport(a.hours,ev))msg('Failed!');}else if(f.kind==='blink')ev.push(...g.applyBlinkSpell(a.dir===undefined?null:['north','south','east','west'][a.dir]));
     }
   } else if(a.kind==='use'&&a.item<16){
     if(a.item<8){if(s.scrollQuantities[a.item]>0)s.scrollQuantities[a.item]--;msg('Scroll');const r=readScroll(s,a.item,s.position.location);r.messages.forEach(msg);if(r.followup.kind==='windDir'&&a.dir!==undefined){s.wind=windForDirection(['north','south','east','west'][a.dir] as any);s.windDriftCtr=0;}else if(r.followup.kind==='resurrect'&&s.characters[a.member])applyResurrect(s.characters[a.member],s.karma);else if(r.followup.kind==='reveal')reveal();if(!r.messages.includes('No effect!'))cue(scrollCeremonyIndex(a.item));}
     else{const color=a.item-8;if(s.potionQuantities[color]>0)s.potionQuantities[color]--;msg('Potion');if(s.characters[a.member]){cue(potionCeremonyIndex(color));const o=applyPotionEffect(s.characters[a.member],rerollPotionColor(color,rng),rng,s.position.location);msg(o.message);if(o.effectiveColor===7&&o.ok)reveal();}}
   } else if(a.kind==='dngAttack')ev=g.dungeonCommand('attack');else if(a.kind==='dngForward')ev=g.dungeonCommand('forward');else if(a.kind==='order')ev=g.newOrder(a.member,a.item);else if(a.kind==='active')ev=g.setActivePlayer(a.member);else if(a.kind==='view')ev=g.view();else if(a.kind==='afterView')ev=g.afterGemView();else if(a.kind==='ignite')ev=g.ignite();else if(a.kind==='board')ev=g.board();else if(a.kind==='disembark')ev=g.exitVehicle();else if(a.kind==='rest')ev=g.camp(a.hours,a.member);else if(a.kind==='pass')ev=g.pass();else if(['move','open','jimmy','push','get','klimb','look','attack'].includes(a.kind))ev=g[a.kind](['north','south','east','west'][a.dir]);else if(a.kind==='use')ev=a.item===32?g.useSpyglass():a.item===16?g.useMagicCarpet():g.useSkullKey(a.dir===undefined?null:['north','south','east','west'][a.dir]);else if(a.kind==='wish')ev=g.makeWish(a.text);else if(a.kind==='fire')ev=a.dir===undefined?g.fireCannon():g.fire(['north','south','east','west'][a.dir]);else if(a.kind==='crystal')ev=g.crystalBall(a.member);else if(a.kind==='coin')ev=g.dropCoin(a.pay);else if(a.kind==='toll')ev=g.resolveTrollToll(a.pay);else if(a.kind==='sails')ev=g.yellSails();else if(a.kind==='end')ev=g.endCombat();
   else for(let i=0;i<a.repeat;i++){const c=g.combat,u=c.currentUnit;if(!u)break;
     if(u.kind!=='player')ce.push(...c.tickEnemyTurnStep());else if(a.kind==='escape')ce.push(...c.playerEscape('south'));else if(a.kind==='quick')ce.push(...c.playerEscapeQuick());else if(a.kind==='flee')ce.push(...c.playerMove('south'));else if(a.kind==='hold')ce.push(...c.playerPass());
     else{const targets=c.combatants.filter((e:any)=>e.kind==='enemy'&&(e.status==='active'||e.status==='sleeping')).sort((a:any,b:any)=>(Math.max(Math.abs(a.x-u.x),Math.abs(a.y-u.y))-Math.max(Math.abs(b.x-u.x),Math.abs(b.y-u.y)))||a.id-b.id),e=targets[0];if(!e)ce.push(...c.playerPass());else if(Math.max(Math.abs(e.x-u.x),Math.abs(e.y-u.y))<=u.attackRange)ce.push(...c.playerAttack(e.x,e.y));else ce.push(...c.playerMove(e.x!==u.x?(e.x>u.x?'east':'west'):(e.y>u.y?'south':'north')));}
   }
   for(const e of ev)coverage[e.kind]=(coverage[e.kind]??0)+1;
   steps.push({events:ev.map(event),combatEvents:ce.map(e=>[e.kind,e.text??'',e.actorId??-1,e.targetId??-1,e.x??-1,e.y??-1,e.damage??-1]),state:projection(structuredClone(s)),...(npcs?{npcs:npcs.npcsAt(s.position.location,s.position.floor).sort((a:any,b:any)=>a.slot-b.slot).map((n:any)=>[n.slot,n.type,n.dialogNumber,n.x,n.y,n.z,n.aiTypes]),npcDead:s.npcDead}:{}),...(scenario.dungeon?{dungeon:{position:g.dungeonState.pos,cells:Array.from({length:512},(_,i)=>{const c=g.dungeonState.cellAt(i>>6,i&7,(i>>3)&7);return c.type*16+c.sub;})}}:{}),seed:g.liveSeed(),combat:battle(g.combat),...(scenario.activeInspect?{activeTiles:scenario.inspectCoords.map(([x,y]:number[])=>g.activeMap.tileAt(x,y))}:{}),...(scenario.inspect?{tiles:scenario.inspectCoords.map(([x,y]:number[])=>g.mapTileWithOverrides(x,y))}:{})});
 };
 if(scenario.actions)for(const a of scenario.actions){if(g.combat&&a.kind==="pass")break;act(a);}
 else for(let i=0;i<12&&!g.combat;i++){
   act({kind:i%3===0?'move':'pass',dir:seed%4});
   if(g.pendingTroll)act({kind:'toll',pay:seed%2===0});
 }
 if(g.combat){act({kind:finish,repeat:finish==='fight'?2000:300});if(g.combat.victory&&!g.combat.over)act({kind:'quick',repeat:100});if(!g.combat.over&&(s.transportTile&248)!==32)act({kind:'escape',repeat:100});const outcome=!g.combat.over?'stillActive':g.combat.victory?'victory':s.characters.slice(0,s.partySize).every((c:any)=>c.status==='D')?'defeat':'flee';coverage[outcome]=(coverage[outcome]??0)+1;if(g.combat.over)act({kind:'end'});}
 inputs.push(q);expected.push(steps);
}
for(const from of [28,29,18,20,32,36,40])for(let seed=0;seed<8;seed++){
 add(seed,from>=32?1:5,s=>{s.transportTile=from;s.transport=transportMode(from);s.time.hour=seed%2?0:12;s.position.x=seed%2?255:10;s.specialItems.hmsCape=!!(seed&2);});
}
for(const index of [0,8,18,39,41,43])for(let seed=0;seed<4;seed++)add(seed,5,s=>{const def=enemyDefs[index]!;s.overworldEnemies=[{defIndex:index,tile:def.tile,water:false,x:10,y:8,...(index===8?{hull:100}:{})}];},false,seed%2?'fight':'flee');
for(let seed=0;seed<128;seed++)add(seed,106+seed%2,s=>{s.characters[0].dexterity=seed%4?1:30;s.characters[0].strength=20;});
for(const from of [28,29,18,20,32,40])for(let seed=0;seed<8;seed++)add(seed,1,s=>{s.transportTile=from;s.transport=transportMode(from);s.shipHull=seed%2?1:99;s.shipSkiffs=seed%3;s.overworldEnemies=[{defIndex:43,tile:492,water:true,x:10,y:9}];});
for(let seed=0;seed<16;seed++)add(seed,1,s=>{s.transportTile=32;s.transport='ship';s.shipHull=seed%2?1:99;s.overworldEnemies=[{defIndex:18,tile:392,water:true,x:12,y:12},{defIndex:39,tile:476,water:true,x:13,y:13}];});
for(let seed=0;seed<24;seed++)add(seed,5,s=>{s.position.x=(seed*11)&255;s.position.y=(seed*17)&255;s.transportTile=20;s.transport='carpet';},true);
for(const tile of [184,185,186,187,151,152,153,175,68])for(let seed=0;seed<8;seed++)add(seed,68,s=>{s.keys=seed%3;s.characters[0].dexterity=seed*4;},false,'flee',{inspect:true,inspectCoords:[[10,9]],edits:[[10,9,tile]],actions:[{kind:'open',dir:0},{kind:'jimmy',dir:0},{kind:'open',dir:0},{kind:'move',dir:0},...Array.from({length:4},()=>({kind:'pass'})),{kind:'move',dir:1},{kind:'move',dir:0}]});
for(const tile of [91,144,145,146,147,165,166,168,169,173,174,175,180,181,182,183,68])for(let dir=0;dir<4;dir++)for(const pull of [false,true]){const [dx,dy]=([[0,-1],[0,1],[1,0],[-1,0]] as const)[dir]!,fill=(tile&252)===180?69:68;add(7,fill,()=>{},false,'flee',{inspect:true,inspectCoords:[[10,10],[10+dx,10+dy],[10+dx*2,10+dy*2]],edits:[[10+dx,10+dy,tile],[10+dx*2,10+dy*2,pull?48:fill]],actions:[{kind:'push',dir},{kind:'push',dir}]});}
for(const contents of [0,1,10,20,30,127,128,138,158,255])for(let seed=0;seed<8;seed++)add(seed,68,s=>{s.keys=seed%3;s.characters[0].dexterity=seed*4;s.worldObjects=[{location:0,floor:0,x:10,y:9,tile:257,kind:'chest',contents,trapped:!!(contents&128)}];},false,'flee',{actions:[{kind:seed%2?'jimmy':'pass',dir:0},{kind:'open',dir:0},...Array.from({length:12},()=>({kind:'get',dir:0}))]});
for(const tile of [154,155,156,45,176,177])for(let dir=0;dir<4;dir++){const [dx,dy]=([[0,-1],[0,1],[1,0],[-1,0]] as const)[dir]!;add(7,68,()=>{},false,'flee',{inspect:true,inspectCoords:[[10+dx,10+dy]],edits:[[10+dx,10+dy,tile]],actions:[{kind:'get',dir},{kind:'get',dir}]});}
for(const tile of [5,12,13])for(let seed=0;seed<16;seed++)add(seed,5,s=>{s.grapple=!!(seed&1);s.characters[0].dexterity=seed;s.transport=seed&2?'carpet':'foot';s.transportTile=seed&2?20:28;},false,'flee',{edits:[[10,9,tile]],actions:[{kind:'klimb',dir:0},{kind:'move',dir:1}]});
for(const from of [28,18,20,32,36,40])for(let seed=0;seed<4;seed++)add(seed,5,s=>{s.transportTile=from;s.transport=transportMode(from);s.magicCarpets=seed%2;},false,'flee',{actions:[{kind:'use',item:16},{kind:'move',dir:2}]});
for(const tile of [151,152,184,185,5])for(const dir of [undefined,0])add(7,68,s=>{s.skullKeys=1;},false,'flee',{inspect:true,inspectCoords:[[10,9]],edits:[[10,9,tile]],actions:[{kind:'use',item:17,dir},{kind:'open',dir:0}]});
for(let tile=0;tile<256;tile++)for(const hour of [0,6,17,18,19])add(7,68,s=>{s.time.hour=hour;},false,'flee',{edits:[[10,9,tile]],actions:[{kind:'look',dir:0}]});
for(let seed=0;seed<40;seed++)add(seed,68,s=>{s.characters[0].intelligence=seed;s.characters[0].currentHp=1;},false,'flee',{actions:[{kind:'crystal',member:0}]});
for(let hour=0;hour<24;hour++)add(7,68,s=>{s.time.hour=hour;},false,'flee',{actions:[{kind:'use',item:32}]});
for(let item=0;item<16;item++)for(let seed=0;seed<16;seed++)add(seed,68,s=>{s.characters[0].currentHp=1;s.characters[0].status=['G','P','S','D'][seed%4];s.potionQuantities.fill(2);s.scrollQuantities.fill(2);},false,'flee',{actions:[{kind:'use',item,member:seed%5===0?-1:0,dir:seed%4}]});
for(let item=0;item<48;item++)if(item!==46)for(let seed=0;seed<8;seed++)add(seed,5,s=>{s.characters[0].currentHp=1;s.characters[0].status=['G','P','S','D'][seed%4];s.characters[0].level=seed%3===0?1:8;s.characters[0].currentMp=seed===1?0:99;s.spellQuantities.fill(seed===2?0:2);if(item===17){s.characters[0].status="G";s.characters[0].currentHp=100;}},false,'flee',{actions:[{kind:'cast',item,caster:0,member:seed%5===0?-1:0,dir:seed%4}]});
for(const item of [6,25])for(const tile of [184,185,186,187,151,152,68])add(7,68,s=>{s.spellQuantities.fill(2);s.characters[0].currentMp=99;s.characters[0].level=8;},false,'flee',{edits:[[10,9,tile]],inspect:true,inspectCoords:[[10,9]],actions:[{kind:'cast',item,caster:0,member:0,dir:0},{kind:'open',dir:0}]});
for(let seed=0;seed<128;seed++)add(seed,5,()=>{},false,'flee',{actions:[{kind:'rest',hours:9,member:-1}]});
for(const item of [0,2,3,4,6,12,14,15,16,18,19,20,21,22,27,29,32,42,47])for(const cell of [0,8,64,65,72,128,136,240])add(7,68,s=>{s.spellQuantities.fill(2);s.characters[0].currentMp=99;s.characters[0].level=8;s.characters[0].currentHp=100;},false,'flee',{dungeon:{location:33,cells:Array(512).fill(cell)},actions:[{kind:'cast',item,caster:0,member:0}]});
for(const from of [28,18,20,32,33,36,40])for(let seed=0;seed<8;seed++)add(seed,seed&1?1:5,s=>{s.transportTile=from;s.transport=transportMode(from);if(seed&2)s.overworldEnemies=[{defIndex:0,tile:448,water:false,x:10,y:9}];},false,'flee',{actions:[{kind:'attack',dir:0}]});
for(const from of [28,32,33,34,35,36,37,40])for(let seed=0;seed<8;seed++)add(seed,1,s=>{s.transportTile=from;s.transport=transportMode(from);if(seed&2)s.overworldEnemies=[{defIndex:8,tile:300,water:true,x:12,y:10,hull:seed&4?1:99}];},false,'flee',{actions:[{kind:'fire',dir:seed%4}]});
for(let item=0;item<16;item++)for(let seed=0;seed<8;seed++)add(seed,5,s=>{s.potionQuantities.fill(2);s.scrollQuantities.fill(2);s.overworldEnemies=[{defIndex:0,tile:448,water:false,x:10,y:9}];},false,'flee',{actions:[{kind:'attack',dir:0},{kind:'cbuse',item}]});
for(const location of [1,22,31])for(const text of ['', 'Horse','horse','Ferrari','a Lotus please','Gold'])for(const tile of [68,77])add(7,68,s=>{s.position.location=location;},false,'flee',{edits:[[11,10,tile]],inspect:true,inspectCoords:[[11,10]],actions:[{kind:'coin',pay:true},{kind:'wish',text}]});
for(const direction of [0,1,2,3])for(const target of [68,151,152,153,184,185,186,187,77]){const [dx,dy]=([[0,-1],[1,0],[0,1],[-1,0]] as const)[direction]!;add(7,68,s=>{s.position.location=1;},false,'flee',{edits:[[10+dx,10+dy,180+direction],[10+dx*3,10+dy*3,target]],inspect:true,inspectCoords:[[10+dx*3,10+dy*3]],actions:[{kind:'fire'}]});}
for(const tile of [157,159,68])add(7,68,s=>{s.position.location=1;},false,'flee',{edits:[[10,9,tile]],inspect:true,inspectCoords:[[10,9]],actions:[{kind:'attack',dir:0},{kind:'attack',dir:0}]});
for(let item=16;item<=37;item++)add(7,5,s=>{s.skullKeys=1;s.overworldEnemies=[{defIndex:0,tile:448,water:false,x:10,y:9}];},false,'flee',{actions:[{kind:'attack',dir:0},{kind:'cbuse',item}]});
for(let item=0;item<49;item++)for(const mask of [0,1,255])for(const hours of [0,1,3])add(7,68,s=>{s.reagentQuantities.fill(2);},false,'flee',{actions:[{kind:'mix',item,mask,hours}]});
for(const tile of [272,273,275,276,277,292,293,294,295,296,297,298,299])for(const land of [false,true])for(let seed=0;seed<4;seed++)add(seed,land?5:1,s=>{s.mapOverrides={'0:0:10:10':tile};s.shipSkiffs=seed%2;s.magicCarpets=seed&2?0:1;},false,'flee',{actions:[{kind:'board'},{kind:'move',dir:2},{kind:'disembark'},{kind:'board'},{kind:'disembark'}]});
for(const dungeon of [false,true])for(const gems of [0,1,2])for(const torches of [0,1,2])add(7,68,s=>{s.gems=gems;s.torches=torches;},false,'flee',{...(dungeon?{dungeon:{location:33,cells:Array(512).fill(0)}}:{}),actions:[{kind:'view'},{kind:'afterView'},{kind:'ignite'},{kind:'view'},{kind:'afterView'}]});
for(const spell of buildSpellDefs(JSON.parse(readFileSync('game/src/core/data/MagicDefinitions.json','utf8'))))for(const quantity of [1,3,99])add(7,68,s=>{s.reagentQuantities.fill(99);s.spellQuantities.fill(98);},false,'flee',{actions:[{kind:'mix',item:spell.index,mask:spell.reagents.reduce((m:number,r:number)=>m|(1<<r),0),hours:quantity}]});
for(const m of realSmallMaps)for(const floor of m.floors){const coords:[number,number][]=[];for(let y=0;y<32;y++)for(let x=0;x<32;x++)if([72,73,135].includes(floor.tiles[y][x]))coords.push([x,y], [x,Math.min(31,y+1)]);if(!coords.length)continue;for(const hour of [4,5,19,20])for(const bridge of [false,true]){const pos=bridge?coords.find(([x,y])=>(floor.tiles[y][x]&254)===72):undefined;const fallback=Math.max(0,floor.tiles.flat().findIndex((t:number)=>t===68));add(7,68,s=>{s.position={location:m.id,floor:floor.z,x:pos?.[0]??fallback%32,y:pos?.[1]??Math.floor(fallback/32)};s.time.hour=hour;s.time.minute=59;},false,'flee',{small:floor.tiles,activeInspect:true,inspect:true,inspectCoords:coords,actions:[{kind:'look',dir:2},{kind:'pass'}]});}}
for(const sign of data.signs){if(sign.x<1||sign.y<0)continue;const map=sign.location===0?(sign.floor===255?underworld:real):realSmallMaps.find((entry:any)=>entry.id===sign.location)?.floors.find((floor:any)=>floor.z===sign.floor||(sign.floor===255&&floor.z===-1))?.tiles;const tile=map?.[sign.y]?.[sign.x];if(![137,138,160,164,248].includes(tile))throw Error(`Sign ${sign.location}:${sign.floor}:${sign.x}:${sign.y} is on tile ${tile}`);add(7,68,s=>{s.position={location:sign.location,floor:sign.floor,x:sign.x-1,y:sign.y};},false,'flee',{sign,edits:[[sign.x,sign.y,tile]],actions:[{kind:'look',dir:2}]});}
for(const location of [0,1])for(const status of ['G','S','P','D'])for(const name of ['','  Iolo  ','Shamino'])for(let digit=0;digit<8;digit++)add(7,68,s=>{s.position.location=location;s.characters.push({...s.characters[0],name,status});s.partySize=2;},false,'flee',{actions:[{kind:'active',member:digit}]});
for(let a=-1;a<5;a++)for(let b=-1;b<5;b++)add(7,68,s=>{s.characters.push({...s.characters[0],name:'Iolo'},{...s.characters[0],name:'Dupre'});s.partySize=3;},false,'flee',{actions:[{kind:'order',member:a,item:b}]});
for(const tile of [28,18,20,32,36,40])for(const phase of [-1,0,3,7,8])for(const floor of [0,255])add(7,5,s=>{s.transportTile=tile;s.transport=transportMode(tile);s.characters[0].currentMp=99;s.characters[0].level=8;s.spellQuantities.fill(2);s.moonstones=Array.from({length:8},(_,i)=>({x:120+i,y:99,z:floor,location:i===3?255:0,buried:true}));},false,'flee',{actions:[{kind:'cast',item:46,caster:0,hours:phase}]});
const realNpcs=JSON.parse(readFileSync('game/assets/npcs.json','utf8'));
const actor=Object.values(realNpcs).flat().find((n:any)=>n.type>=64&&n.type<128) as any;
for(const kind of ['look','attack','jimmy','fire'])for(const type of [64,120,128,180,216,232,252])for(const tile of [68,132,133,159,171])add(7,68,s=>{s.position.location=1;s.keys=2;s.characters[0].dexterity=30;},false,'flee',{npcs:[{...actor,slot:1,type,aiTypes:[0,0,0],x:[10,10,10],y:[9,9,9],z:[0,0,0],times:[0,0,0,0]}],edits:[[10,9,tile],[10,11,180]],actions:[{kind,dir:kind==='fire'?undefined:0}]});
for(let seed=0;seed<16;seed++)add(seed,5,s=>{s.characters[0].currentHp=1;s.characters[0].dexterity=1;s.overworldEnemies=[{defIndex:0,tile:448,water:false,x:10,y:9}];},false,'hold',{actions:[{kind:'attack',dir:0}]});
for(const size of [8,16,31])for(let seed=0;seed<16;seed++)add(seed,5,s=>{s.worldObjects=Array.from({length:size},(_,i)=>({kind:'prop',location:0,floor:0,x:(i*7)&255,y:(i*11)&255,tile:257,slot:i+1}));s.overworldEnemies=[{defIndex:0,tile:448,water:false,x:255,y:255},{defIndex:1,tile:260,water:false,x:200,y:200}];},false,'flee',{actions:Array.from({length:24},()=>({kind:'pass'}))});
for(const [i,source] of JSON.parse(readFileSync('game/assets/maps/combatmaps.json','utf8')).slice(16).entries()){const location=33+Math.floor(i/16)+(i>=16?1:0),cells=Array(512).fill(0);cells[3*64+2*8+3]=240+(i%16);add(7,5,()=>{},false,'flee',{room:{...source,index:16+i},dungeon:{location,cells},actions:[{kind:'dngForward'}]});}
for(const location of [33,34,36,40])for(const wanderer of [1,4,12,18,39,43])for(const seed of [1,7])add(seed,5,()=>{},false,'flee',{dungeon:{location,cells:Array(512).fill(0),wanderer},actions:[{kind:'dngAttack'}]});
for(let seed=0;seed<128;seed++)add(seed,5,()=>{},false,'flee',{dungeon:{location:33,cells:Array(512).fill(0)},actions:[{kind:'rest',hours:9,member:-1}]});
const totalSequences=inputs.length;const realCoverage={townHourSequences:inputs.filter(q=>q.small).length,signSequences:inputs.filter(q=>q.sign).length,dungeonRoomSequences:inputs.filter(q=>q.room).length,corridorSequences:inputs.filter(q=>q.dungeon?.wanderer).length};
const start=Number(process.env.GAMEPLAY_START??0);if(start){inputs.splice(0,start);expected.splice(0,start);}
writeFileSync(dir+'/input.jsonl',inputs.map(q=>JSON.stringify(q)).join('\n')+'\n');
const run=spawnSync(process.argv[2]??'native/core/build-zig/gameplay_driver.exe',[dir+'/input.jsonl',dir+'/actual.jsonl',dir+'/assets.json'],{encoding:'utf8'});
if(run.status!==0)throw Error(run.stderr||String(run.error||run.status));
const actual=readFileSync(dir+'/actual.jsonl','utf8').trim().split('\n').map(s=>JSON.parse(s));
if(actual.length!==expected.length)throw Error('Sequence count mismatch');
const nativeOnlyAudioHooks=new Set(['spell-cast','scroll-used','potion-used','invalid-magic']);
for(let i=0;i<actual.length;i++){for(const step of actual[i]){step.state=projection(step.state);step.events=step.events.filter((e:any)=>!(e.kind==='sfx'&&nativeOnlyAudioHooks.has(e.text)));}if(!isDeepStrictEqual(actual[i],expected[i])){writeFileSync(dir+'/mismatch.json',JSON.stringify({i,input:inputs[i],actual:actual[i],expected:expected[i]},null,2));throw Error(`Gameplay mismatch ${i}`);}}
if(!start)for(const required of ['victory','flee','defeat','refuge','troll-toll-prompt'])if(!coverage[required])throw Error('Missing outcome witness '+required);
writeFileSync(dir+'/coverage.json',JSON.stringify({sequences:inputs.length,totalSequences,realCoverage,coverage},null,2));console.log({sequences:inputs.length,totalSequences,realCoverage,coverage});
