/** Execute authoritative TS functions; never a second implementation of their rules. */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { OriginalRng, timeHashSeed } from '../../../game/src/core/rng-original.js';
import { advanceMinutes, dayPhase, scheduleIndex } from '../../../game/src/core/time.js';
import { createNewGame, type ExtractedInitialState, type GameState } from '../../../game/src/core/state.js';
import { partyMembers, firstConsciousIndex } from '../../../game/src/core/party.js';
import { getActiveMap, wrapCoord, type WorldData } from '../../../game/src/core/world/map.js';
import { DIRECTION_DELTA, isPassable, resolveStep, terrainSpeedClass } from '../../../game/src/core/world/movement.js';
import { TILE_INFO } from '../../../game/src/core/tiles.js';

const base = new URL('../', import.meta.url);
const check = process.argv.includes('--check');
function output(path: string, text: string) {
  const file = fileURLToPath(new URL(path, base));
  if (check) {
    if (readFileSync(file, 'utf8') !== text) throw new Error(`Reference drift: ${path}. Review TS changes before regenerating.`);
  } else writeFileSync(file, text);
}
const phases = ['night', 'dawn', 'day', 'dusk'];
const directions = ['north', 'south', 'east', 'west'] as const;
const transports = ['foot', 'horse', 'carpet', 'skiff', 'ship'] as const;
const messages = [null, 'Blocked!', 'Slow progress!', 'Very slow!'];
const tables: Record<string, number[][]> = {};

tables.rng = [];
for (const seed of [0, 1, 0x9248, 0xffff, -1, 0x12345678]) {
  const r = new OriginalRng(seed);
  for (let i = 0; i < 96; i++) {
    const [lo, hi] = [[1, 8], [0, 0], [-100, 99], [1, 0], [0, 65535], [-2147483648, 2147483647]][i % 6]!;
    const before = r.getSeed();
    let value = 0, error = 0;
    try { value = r.next(lo!, hi!); } catch { error = 1; }
    tables.rng.push([before, lo!, hi!, value, error, r.getSeed()]);
  }
}
// Exhaustive one-step word-domain digest plus multi-step raw chain.
let rawHash = 2166136261;
for (let seed = 0; seed < 65536; seed++) rawHash = Math.imul(rawHash ^ new OriginalRng(seed).nextRaw16(), 16777619) >>> 0;
tables.rawHash = [[rawHash]];
tables.raw = [];
const raw = new OriginalRng(0);
for (let i = 0; i < 512; i++) tables.raw.push([raw.nextRaw16()]);
tables.seed = [-2147483648, -65537, -1, 0, 65535, 65536, 2147483647].map(n => [n, new OriginalRng(n).getSeed()]);
tables.hash = [[0,0,0,0], [23,59,59,99], [-1,-1,-1,-1], [255,256,511,1024], [12,34,56,78]].map(v => [...v, timeHashSeed(...v as [number,number,number,number])]);
tables.time = [];
for (const t of [
  {year:139, month:1, day:1, hour:0, minute:0},
  {year:139, month:13, day:28, hour:23, minute:59},
  {year:139, month:2, day:28, hour:5, minute:59},
  {year:139, month:14, day:29, hour:24, minute:60},
]) for (const minutes of [-61, -1, 0, 1, 2, 60, 1440, 524160, 1048321]) {
  const out = advanceMinutes(t, minutes);
  tables.time.push([...Object.values(t), minutes, ...Object.values(out), phases.indexOf(dayPhase(out))]);
}
tables.phase = Array.from({length:28}, (_,i) => [i-2, phases.indexOf(dayPhase({year:0,month:1,day:1,hour:i-2,minute:0}))]);
tables.schedule = [];
for (const times of [[0,6,12,18], [6,6,6,6], [255,0,128,250], [20,5,13,23]])
  for (let hour = 0; hour < 256; hour++) tables.schedule.push([...times, hour, scheduleIndex(times, hour)]);
tables.tiles = [];
for (const tile of [-2, -1, ...Array.from({length:TILE_INFO.length+2}, (_,i) => i), 65535]) {
  for (let mode = 0; mode < transports.length; mode++) {
    let value = false, error = 0;
    try { value = isPassable(tile, transports[mode]!); } catch { error = 1; }
    tables.tiles.push([tile, mode, +value, error, terrainSpeedClass(tile)]);
  }
}
const tileFlags = Array.from({length:TILE_INFO.length}, (_,i) => {
  const t = TILE_INFO[i];
  return t ? +t.walkable | (+t.horsePassable << 1) | (+t.skiffPassable << 2) | (+t.boatPassable << 3) : 255;
});
output('src/tile_flags.inc', '// Generated by tools/generate-fixtures.ts from final TILE_INFO. See data/ATTRIBUTION.txt.\nstatic constexpr uint8_t kTileFlags[] = {\n' + tileFlags.map((n,i) => `${i%24===0?'    ':''}${n},${i%24===23?'\n':' '}`).join('') + '\n};\n');
const world: WorldData = {
  overworld: Array.from({length:256},(_,y)=>Array.from({length:256},(_,x)=>(x+y*3)&255)),
  underworld: Array.from({length:256},(_,y)=>Array.from({length:256},(_,x)=>(x*7+y)&255)),
  smallMaps: new Map([[13,{id:13,name:'Synthetic',floors:[{z:-1,tiles:Array.from({length:32},(_,y)=>Array.from({length:32},(_,x)=>x===31&&y===31?255:x^y))}]}]]),
};
tables.wrap = [-2147483648,-1025,-257,-256,-1,0,255,256,257,2147483647].map(v=>[v,wrapCoord(v)]);
tables.map = [];
for (const [location,floor] of [[0,0],[0,255],[0,-1],[13,-1],[13,0],[1,0]]) {
  for (const [x,y] of [[0,0],[31,31],[-1,0],[32,15],[255,256],[-257,512]]) {
    try {
      const m = getActiveMap(world,location!,floor!);
      tables.map.push([location!,floor!,x!,y!,0,['overworld','underworld','small'].indexOf(m.kind),m.width,m.height,+m.wraps,m.edgeFillTile,m.tileAt(x!,y!)]);
    } catch { tables.map.push([location!,floor!,x!,y!,1,0,0,0,0,0,0]); }
  }
}
tables.direction = directions.map((d,i)=>[i,DIRECTION_DELTA[d].dx,DIRECTION_DELTA[d].dy]);
tables.movement = [];
for (const wraps of [false,true]) for (let tile=0;tile<256;tile++) for (let d=0;d<4;d++) {
  const positions = [[15,15], ...(tile===5 || tile===255 ? [[0,0],[31,31],[255,255]] : [])];
  for (const [x,y] of positions) {
    if (!wraps && (x!>31 || y!>31)) continue;
    const state = {position:{location:wraps?0:13,floor:0,x:x!,y:y!},transport:'foot',time:{year:139,month:13,day:28,hour:23,minute:59},turnsSinceStart:123} as GameState;
    const m = {kind:wraps?'overworld':'small',location:state.position.location,floor:0,width:wraps?256:32,height:wraps?256:32,wraps,tileAt:()=>tile,edgeFillTile:255} as const;
    const result = resolveStep(state,m,directions[d]!);
    // resolveStep returns a result and emits no Game events; Game.move remains untranslated.
    tables.movement.push([+wraps,tile,d,x!,y!,state.position.x,state.position.y,+result.moved,+result.blocked,+result.exitedMap,messages.indexOf(result.message),result.minutes,result.speedClass,+result.onBridge,+result.onSwamp,+result.onCactus,0]);
  }
}
tables.party = [];
for (let count=0;count<=16;count++) for (const size of [-1,0,1,3,6,9,16]) {
  const characters = Array.from({length:count},(_,i)=>({partyStatus:i%3===1?255:0,status:['D','S','P','G','C'][i%5]}));
  const state = {characters,partySize:size} as GameState;
  const indices = partyMembers(state).map(c=>state.characters.indexOf(c));
  tables.party.push([count,size,firstConsciousIndex(state),indices.length,...Array.from({length:6},(_,i)=>indices[i]??-1)]);
}
// Synthetic INIT projection; no original game files required or embedded.
const init = {
  characters:Array.from({length:16},(_,i)=>({name:`Test${i}`,gender:11,class:i===0?'A':'B',status:i%2?'P':'G',strength:i+10,dexterity:i+11,intelligence:i+12,currentMp:i,currentHp:100+i,maxHp:200+i,exp:1000+i,level:3,monthsAtInn:2,helmet:1,armor:2,weapon:3,shield:4,ring:5,amulet:6,partyStatus:i<3?0:255})),
  partySize:3,activeCharacter:255,food:321,gold:432,torchTurns:17,karma:77,turnsSinceStart:12345,
  year:139,month:13,day:28,hour:23,minute:59,location:13,floor:-1,x:15,y:15,
  equipmentQuantities:[],spellQuantities:[],scrollQuantities:[],potionQuantities:[],reagentQuantities:[],specialItems:{},shards:{},lbArtifacts:{},moonstones:[],npcDead:[],npcMet:[],
} as unknown as ExtractedInitialState;
const state = createNewGame(init);
tables.initial = [[state.version,state.partySize,state.activeCharacter,state.food,state.gold,state.torchTurns,state.karma,state.turnsSinceStart,...Object.values(state.time),state.position.location,state.position.floor,state.position.x,state.position.y,transports.indexOf(state.transport)]];
tables.characters = state.characters.map(c=>[c.gender,c.class.charCodeAt(0),c.status.charCodeAt(0),c.strength,c.dexterity,c.intelligence,c.currentMp,c.currentHp,c.maxHp,c.exp,c.level,c.monthsAtInn,c.helmet,c.armor,c.weapon,c.shield,c.ring,c.amulet,c.partyStatus]);
tables.names = state.characters.map(c=>Array.from({length:9},(_,i)=>c.name.charCodeAt(i)||0));
tables.sequence = [];
const replay = createNewGame(init);
const replayRng = new OriginalRng(0x1234);
const replayMap = {kind:'small',location:13,floor:-1,width:32,height:32,wraps:false,
  tileAt:(x:number,y:number)=>[5,5,5,0x94,4,0x6a,0x2f][(x+3*y)%7]!,edgeFillTile:255} as const;
for (let i=0;i<120;i++) {
  const kind = i%5===0 ? 0 : i%5===1 ? 1 : 2;
  const a = kind===0 ? -7 : kind===1 ? [1,60,-1,1440][Math.floor(i/5)%4]! : Math.floor(i/12)%4;
  const b = kind===0 ? 9 : 0;
  let value=0;
  let move = [0,0,0,0,0,0,0,0,0];
  if (kind===0) value=replayRng.next(a,b);
  else if (kind===1) replay.time=advanceMinutes(replay.time,a);
  else {
    const r=resolveStep(replay,replayMap,directions[a]!);
    move=[+r.moved,+r.blocked,+r.exitedMap,messages.indexOf(r.message),r.minutes,r.speedClass,+r.onBridge,+r.onSwamp,+r.onCactus];
  }
  tables.sequence.push([kind,a,b,value,replay.position.x,replay.position.y,...Object.values(replay.time),replayRng.getSeed(),replay.partySize,replay.characters[0]!.currentHp,replay.turnsSinceStart,replay.position.location,replay.position.floor,...move,0]);
  // All other foundation fields must remain equal, not merely the selected trace columns.
  if (JSON.stringify(replay.characters)!==JSON.stringify(state.characters) ||
      replay.version!==1 || replay.transport!=='foot' || replay.partySize!==3 || replay.activeCharacter!==255 ||
      replay.food!==321 || replay.gold!==432 || replay.torchTurns!==17 || replay.karma!==77)
    throw new Error(`Unexpected foundation mutation at sequence action ${i}`);
}
const fixtures = {schema:1,scope:'foundation; resolveStep foot/actorTile=0; no Game.move events',tables};
output('fixtures/foundation.json',JSON.stringify(fixtures,null,2)+'\n');
let header = '// Generated from live TypeScript reference. Do not edit.\n';
for (const [name,rows] of Object.entries(tables)) header += `static constexpr int64_t f_${name}[][${rows[0]!.length}] = {\n${rows.map(r=>'    {'+r.join(',')+'},').join('\n')}\n};\n`;
output('fixtures/foundation.inc',header);
console.log(`${check?'Verified':'Generated'} ${Object.values(tables).reduce((n,r)=>n+r.length,0)} reference cases; exhaustive 65536-seed RNG digest.`);
