import {readFileSync, writeFileSync} from 'node:fs';
const rows:string[]=[];
for(let cp=0;cp<=0x10ffff;cp++) {
  const s=String.fromCodePoint(cp), upper=s.toUpperCase();
  if(s===upper) continue;
  const out=Array.from(upper,c=>c.codePointAt(0)!);
  if(out.length>3) throw new Error('Uppercase expansion exceeds table capacity');
  rows.push(`{${cp},{${out.join(',')}},${out.length}},`);
}
const path='native/core/src/quest_case.inc';
const text='// Generated by generate-quest-case.ts using the reference JavaScript Unicode uppercase.\n'+rows.join('\n')+'\n';
if(process.argv.includes('--check')) { if(readFileSync(path,'utf8')!==text) throw new Error('Quest case table drift'); }
else writeFileSync(path,text);
